/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  extraTime: string;
  footballTimelineMinute: string;
  hiddenMiddle: string;
  middle: string;
  middleNotification: string;
  minute: string;
  minuteLine: string;
  sides: string;
}
export const cssExports: CssExports;
export default cssExports;
