/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeBackground: string;
  activeLogoImage: string;
  activeRightContainerWidget: string;
  backgroundImageContainer: string;
  button: string;
  container: string;
  contentContainer: string;
  gameBadgeContainer: string;
  leftContentWidget: string;
  moreInfoLink: string;
  rightContainerWidget: string;
  rightContentWidget: string;
  staticBackground: string;
  staticContainer: string;
  staticLogoImage: string;
  subtitle: string;
  timerContainer: string;
  title: string;
  titleContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
