/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content: string;
  header: string;
  myBetsHeader: string;
  myBetsHeaderAddOn: string;
  sectionContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
