/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betInfoCollapse: string;
  betInfoHeader: string;
  betInfoHeaderIcon: string;
  betInfoHeaderTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
