/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionLink: string;
  content: string;
  header: string;
  image: string;
  loyaltyMessage: string;
  modal: string;
  modalContainer: string;
  overlay: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
