/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bar: string;
  caption: string;
  condensed: string;
  incident: string;
  incidents: string;
  inplay: string;
  timelineBar: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
