/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionIcon: string;
  betSummaryContainer: string;
  focusedContent: string;
  focusedContentVisible: string;
  headerContainer: string;
  headerSubtitle: string;
  headerSubtitleCollapsed: string;
  headerSubtitleInfo: string;
  headerSubtitleInfoPriceBoostMultiple: string;
  headerSubtitleMore: string;
  headerTitle: string;
  oddsMovementAlertContainer: string;
  operatorInfo: string;
  placeButton: string;
  quickStakesContainer: string;
  sheetContainer: string;
  sheetContent: string;
  sheetContentCollapsed: string;
  sheetContentExpanded: string;
  sheetFooter: string;
  sheetFooterCollapsed: string;
  sheetHeader: string;
  sheetWrapper: string;
  stakeInput: string;
  subtitleBoldPart: string;
  termsContainer: string;
  titleBoldPart: string;
  titleOpaquePart: string;
  titleText: string;
  webWrappedVersion: string;
}
export const cssExports: CssExports;
export default cssExports;
