/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  groupContainer: string;
  itemsList: string;
  searchBar: string;
  searchTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
