/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  collapsedHeader: string;
  collapsedHeaderAction: string;
  collapsedHeaderContent: string;
  collapsedIcon: string;
  minimizedSupportingText: string;
  minimizedTitle: string;
  webWrappedVersion: string;
}
export const cssExports: CssExports;
export default cssExports;
