/**
 * DON'T EDIT THIS FILE
 * THIS FILE IS GENERATED BY THE TASK `generate-blh-response-types`
 */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
};

/**  The Resulted Bet */
export type BetResult = {
  __typename?: "BetResult";
  legs: Array<Leg>;
  result: Result;
  /**  The result of this bet */
  resultType: ResultType;
};

export enum BetType {
  CANADIAN = "CANADIAN",
  DOUBLE = "DOUBLE",
  EIGHTEENFOLD = "EIGHTEENFOLD",
  EIGHTFOLD = "EIGHTFOLD",
  ELEVENFOLD = "ELEVENFOLD",
  FIFTEENFOLD = "FIFTEENFOLD",
  FIVEFOLD = "FIVEFOLD",
  FOURFOLD = "FOURFOLD",
  FOURTEENFOLD = "FOURTEENFOLD",
  GOLIATH = "GOLIATH",
  HEINZ = "HEINZ",
  LUCKY_15 = "LUCKY_15",
  LUCKY_31 = "LUCKY_31",
  LUCKY_63 = "LUCKY_63",
  MANUAL = "MANUAL",
  NINEFOLD = "NINEFOLD",
  NINETEENFOLD = "NINETEENFOLD",
  PATENT = "PATENT",
  SEVENFOLD = "SEVENFOLD",
  SEVENTEENFOLD = "SEVENTEENFOLD",
  SINGLE = "SINGLE",
  SIXFOLD = "SIXFOLD",
  SIXTEENFOLD = "SIXTEENFOLD",
  SUPER_HEINZ = "SUPER_HEINZ",
  TENFOLD = "TENFOLD",
  THIRTEENFOLD = "THIRTEENFOLD",
  TREBLE = "TREBLE",
  TRIXIE = "TRIXIE",
  TWELVEFOLD = "TWELVEFOLD",
  TWENTYFIVEFOLD = "TWENTYFIVEFOLD",
  TWENTYFOLD = "TWENTYFOLD",
  TWENTYFOURFOLD = "TWENTYFOURFOLD",
  TWENTYONEFOLD = "TWENTYONEFOLD",
  TWENTYTHREEFOLD = "TWENTYTHREEFOLD",
  TWENTYTWOFOLD = "TWENTYTWOFOLD",
  YANKEE = "YANKEE",
}

/**  Game Data from Rich Content */
export type GameData = {
  __typename?: "GameData";
  /**  Away Team Name */
  awayName: Maybe<Scalars["String"]["output"]>;
  /**  Home Team Score */
  awayScore: Maybe<Scalars["Int"]["output"]>;
  /**  Game Minute */
  homeName: Maybe<Scalars["String"]["output"]>;
  /**  Home Team Name */
  homeScore: Maybe<Scalars["Int"]["output"]>;
  minute: Maybe<Scalars["Int"]["output"]>;
};

/**  Input Bet Projection used for Result Calculation */
export type InputBet = {
  betType: BetType;
  legs: Array<InputLeg>;
};

/**  Input Bet Leg used for Result Calculation */
export type InputLeg = {
  legNumber: Scalars["ID"]["input"];
  runners: Array<InputRunner>;
};

/**  Input Leg Runner used for Result Calculation */
export type InputRunner = {
  id: Scalars["ID"]["input"];
  /**  SPORTEX Id of the Runner */
  marketId: Scalars["ID"]["input"];
  /**  Sportsbook Id of the Market */
  result: InputMaybe<Result>;
};

/**  Bet Leg for Result Calculation */
export type Leg = {
  __typename?: "Leg";
  legNumber: Scalars["ID"]["output"];
  runners: Array<Runner>;
};

/**  The Resulted Bet Leg */
export type LegResult = {
  __typename?: "LegResult";
  /**  The source of this runner's result */
  gameData: Maybe<GameData>;
  legNumber: Scalars["ID"]["output"];
  result: Result;
  /**  The result of this runner */
  resultType: ResultType;
};

export type Query = {
  __typename?: "Query";
  betsResult: Array<BetResult>;
  legsResult: Array<LegResult>;
};

export type QueryBetsResultArgs = {
  bets: Array<InputBet>;
};

export type QueryLegsResultArgs = {
  legs: Array<InputLeg>;
};

/**
 *  -------------------- Win/Lose Project Schema ------------------------------------- #
 *  The possible results for a Bet/Leg
 */
export enum Result {
  /**  Winning Bet/Leg */
  LOSE = "LOSE",
  /**  Voided Bet/Leg */
  PENDING = "PENDING",
  /**  Losing Bet/Leg */
  VOID = "VOID",
  WIN = "WIN",
}

/**  How the Bet/Leg Result was Calculated */
export enum ResultType {
  CONFIRMED = "CONFIRMED",
  /**  Result received from either Catalog or Channels */
  POTENTIAL = "POTENTIAL",
  /**  Potential Result based on Real World Data */
  UNKNOWN = "UNKNOWN",
}

/**  The Resulted Leg Runner */
export type Runner = {
  __typename?: "Runner";
  id: Scalars["ID"]["output"];
  /**  SPORTEX Id of the Runner */
  marketId: Scalars["ID"]["output"];
  /**  Sportsbook Id of the Market */
  result: Result;
  /**  The result of this runner */
  resultType: ResultType;
};

export type BetsResultQueryVariables = Exact<{
  bets: Array<InputBet> | InputBet;
}>;

export type BetsResultQuery = {
  __typename?: "Query";
  betsResult: Array<{
    __typename?: "BetResult";
    resultType: ResultType;
    result: Result;
    legs: Array<{
      __typename?: "Leg";
      legNumber: string;
      runners: Array<{ __typename?: "Runner"; id: string; marketId: string; result: Result; resultType: ResultType }>;
    }>;
  }>;
};
