/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footerTextContainer: string;
  freeSpinsPromo: string;
  linkControlsContainer: string;
  optInPromo: string;
  progressBar: string;
  promoCard: string;
  promoCardContent: string;
  promotionCompletedContainer: string;
  remainingText: string;
  remainingTextContainer: string;
  remainingTextFooter: string;
  requirementsText: string;
  tcTextContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
