/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  footerContainer: string;
  freeBetsContainer: string;
  oddsMovementAlertContainer: string;
  removeButton: string;
  screenReaderOnly: string;
  summaryContainer: string;
  termsContainer: string;
  trashIcon: string;
}
export const cssExports: CssExports;
export default cssExports;
