/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  cashBalances: string;
  iconWrapper: string;
  lastLogin: string;
  rewardsCardContainer: string;
  rewardsContainer: string;
  sectionGroupMenu: string;
  title: string;
  userProfile: string;
}
export const cssExports: CssExports;
export default cssExports;
