/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  acceptPromo: string;
  tcText: string;
  textBackground: string;
  textContent: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
