/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  highlightedText: string;
  logoContainer: string;
  logoIconContainer: string;
  logoTextContainer: string;
  logoTextSecondLineContainer: string;
  logoTextSecondLineText: string;
  supportingText: string;
  topContainer: string;
  trackingCounter: string;
  trackingCounterValueIconWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
