/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  byTimeRangeMeeting: string;
  competitionViewLink: string;
  container: string;
  extended: string;
  game: string;
  gamingLink: string;
  highlightedContainer: string;
  highlightedSelection: string;
  navigation: string;
  promoCard: string;
  scrollableSwimlaneLeft: string;
  scrollableSwimlaneRight: string;
  snap: string;
  sportviewlink: string;
  subtitle: string;
  supportingContent: string;
  swimlaneItemContainer: string;
  title: string;
  titleContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
