import normalizer from "./account-banners-card-normalizer";

const BFF_RESPONSE = {
  __typename: "AccountBannersCard",
  urn: "ppb:tbd:card:accountBanners:myaccount#accountBanners",
  bannerDetails: [
    {
      bannerInfo: {
        title: "News banner title",
        bodyContent: {
          text: "New banner body text",
          items: null,
          formContent: null,
          contactUsInfo: null,
        },
      },
      minimizedBannerInfo: {
        bodyText: "New banner body text",
      },
      bannerActions: [
        {
          label: "Find out more",
          gaLabel: null,
          minimizedLabel: "Find out more",
          type: "button",
          buttonType: "PRIMARY",
          path: "/myaccount/test",
          url: "https://www.betfair.com/",
          target: "_blank",
          action: null,
          data: null,
          actionFinalize: null,
        },
        {
          label: "Dismiss",
          gaLabel: null,
          minimizedLabel: "Dismiss",
          type: "button",
          buttonType: "SECONDARY",
          path: "https://myaccount.nxt.com.betfair/usp/set",
          url: "https://www.betfair.com/",
          target: "api",
          action: "UPDATE_USER_PREFERENCE",
          data: '{"preferenceKey": "maw.news.banner","value":"958"}',
          actionFinalize: null,
        },
      ],
      isMinimized: true,
      priority: "2120",
      useCase: "DEFAULT",
      flow: "TBD",
      template: null,
      attentionLevel: "INFO",
      maxDisplays: null,
      version: 958,
      isClosable: null,
      bannerType: "news",
    },
    {
      bannerInfo: {
        title: "Please confirm your new All Products Loss Limit of £80 per day for it to take effect.",
        bodyContent: {
          text: "You updated your limit on 24/09/2020.",
          items: null,
          formContent: null,
          contactUsInfo: null,
        },
      },
      minimizedBannerInfo: {
        bodyText: "",
      },
      bannerActions: [
        {
          label: "Cancel",
          gaLabel: "all products - daily - 80",
          minimizedLabel: null,
          type: "button",
          buttonType: "SECONDARY",
          path: "/api/lossLimits/confirm",
          url: "https://playerprotection.nxt.com.betfair",
          target: "api",
          action: "ACCEPT_OR_CANCEL_LOSS_LIMIT",
          data: '{"productName": "GLOBAL","confirmed": "false"}',
          actionFinalize: {
            onErrorBanner: {
              bannerInfo: {
                title: "Sorry, something went wrong",
                bodyContent: {
                  text: "We were unable to cancel your pending limit. Please try again later.",
                  items: null,
                  formContent: null,
                  contactUsInfo: null,
                },
              },
              minimizedBannerInfo: null,
              bannerActions: [
                {
                  label: "Dismiss",
                  gaLabel: null,
                  minimizedLabel: null,
                  type: "button",
                  buttonType: null,
                  path: null,
                  url: null,
                  target: "close",
                  action: null,
                  data: null,
                },
              ],
              isMinimized: null,
              priority: null,
              useCase: null,
              flow: null,
              template: null,
              attentionLevel: "WARNING",
              maxDisplays: null,
              version: null,
              isClosable: null,
            },
          },
        },
        {
          label: "Confirm",
          gaLabel: "all products - daily - 80",
          minimizedLabel: null,
          type: "button",
          buttonType: "PRIMARY",
          path: "/api/lossLimits/confirm",
          url: "https://playerprotection.nxt.com.betfair",
          target: "api",
          action: "ACCEPT_OR_CANCEL_LOSS_LIMIT",
          data: '{"productName": "GLOBAL","confirmed": "true"}',
          actionFinalize: {
            onErrorBanner: {
              bannerInfo: {
                title: "Sorry, something went wrong",
                bodyContent: {
                  text: "We were unable to confirm your pending limit. Please try again later.",
                  items: null,
                  formContent: null,
                  contactUsInfo: null,
                },
              },
              minimizedBannerInfo: null,
              bannerActions: [
                {
                  label: "Dismiss",
                  gaLabel: null,
                  minimizedLabel: null,
                  type: "button",
                  buttonType: null,
                  path: null,
                  url: null,
                  target: "close",
                  action: null,
                  data: null,
                },
              ],
              isMinimized: null,
              priority: null,
              useCase: null,
              flow: null,
              template: null,
              attentionLevel: "WARNING",
              maxDisplays: null,
              version: null,
              isClosable: null,
            },
          },
        },
      ],
      isMinimized: null,
      priority: "3120",
      useCase: "LOSS_LIMIT",
      flow: "TBD",
      template: null,
      attentionLevel: "WARNING",
      maxDisplays: null,
      version: null,
      isClosable: null,
      bannerType: "rg",
    },
    {
      bannerInfo: {
        title: "Verify Number",
        bodyContent: {
          text: "Did you know you can enhance the security of your account by verifying your phone number?",
          items: null,
          formContent: null,
          contactUsInfo: null,
        },
      },
      minimizedBannerInfo: {
        bodyText: "Did you know you can enhance the security of your account by verifying your phone number?",
      },
      bannerActions: [
        {
          label: "Verify Number",
          gaLabel: null,
          minimizedLabel: "Verify Number",
          type: "button",
          buttonType: "PRIMARY",
          path: "/accountdetails/mydetails?shouldVerifyPhone=true",
          url: "https://myaccount.nxt.internal:443/accountdetails/mydetails?shouldVerifyPhone=true&flow=tbd",
          target: "_top",
          action: null,
          data: null,
          actionFinalize: null,
        },
      ],
      isMinimized: true,
      priority: "4120",
      useCase: "DEFAULT",
      flow: "TBD",
      template: null,
      attentionLevel: "WARNING",
      maxDisplays: null,
      version: null,
      isClosable: false,
      bannerType: "phone",
    },
  ],
};

describe("Account banners card normalizer", () => {
  describe("normalizeAccountBannersCardFragmentIntoAccountBannersCard", () => {
    it("should correctly transform and return the data object", () => {
      const { data } = normalizer(BFF_RESPONSE);

      expect(data).toEqual({
        typename: "AccountBannersCard",
        urn: "ppb:tbd:card:accountBanners:myaccount#accountBanners",
        bannerDetails: [
          {
            index: 0,
            bannerInfo: {
              title: "News banner title",
              bodyContent: {
                text: "New banner body text",
                items: null,
                formContent: null,
                contactUsInfo: null,
              },
            },
            minimizedBannerInfo: {
              bodyText: "New banner body text",
            },
            bannerActions: [
              {
                label: "Find out more",
                gaLabel: null,
                minimizedLabel: "Find out more",
                type: "button",
                buttonType: "PRIMARY",
                path: "/myaccount/test",
                url: "https://www.betfair.com/",
                target: "_blank",
                action: null,
                data: null,
                actionFinalize: {
                  onErrorBanner: null,
                },
              },
              {
                label: "Dismiss",
                gaLabel: null,
                minimizedLabel: "Dismiss",
                type: "button",
                buttonType: "SECONDARY",
                path: "https://myaccount.nxt.com.betfair/usp/set",
                url: "https://www.betfair.com/",
                target: "api",
                action: "UPDATE_USER_PREFERENCE",
                data: '{"preferenceKey": "maw.news.banner","value":"958"}',
                actionFinalize: {
                  onErrorBanner: null,
                },
              },
            ],
            isMinimized: true,
            priority: "2120",
            useCase: "DEFAULT",
            flow: "TBD",
            template: null,
            attentionLevel: "INFO",
            maxDisplays: null,
            version: 958,
            isClosable: null,
            bannerType: "news",
          },
          {
            index: 1,
            bannerInfo: {
              title: "Please confirm your new All Products Loss Limit of £80 per day for it to take effect. 1/1",
              bodyContent: {
                text: "You updated your limit on 24/09/2020.",
                items: null,
                formContent: null,
                contactUsInfo: null,
              },
            },
            minimizedBannerInfo: {
              bodyText: "",
            },
            bannerActions: [
              {
                label: "Cancel",
                gaLabel: "all products - daily - 80",
                minimizedLabel: null,
                type: "button",
                buttonType: "SECONDARY",
                path: "/api/lossLimits/confirm",
                url: "https://playerprotection.nxt.com.betfair",
                target: "api",
                action: "ACCEPT_OR_CANCEL_LOSS_LIMIT",
                data: '{"productName": "GLOBAL","confirmed": "false"}',
                actionFinalize: {
                  onErrorBanner: {
                    index: 1,
                    bannerInfo: {
                      title: "Sorry, something went wrong",
                      bodyContent: {
                        text: "We were unable to cancel your pending limit. Please try again later.",
                        items: null,
                        formContent: null,
                        contactUsInfo: null,
                      },
                    },
                    minimizedBannerInfo: null,
                    bannerActions: [
                      {
                        label: "Dismiss",
                        gaLabel: null,
                        minimizedLabel: null,
                        type: "button",
                        buttonType: null,
                        path: null,
                        url: null,
                        target: "close",
                        action: null,
                        data: null,
                      },
                    ],
                    isMinimized: null,
                    priority: null,
                    useCase: null,
                    flow: null,
                    template: null,
                    attentionLevel: "WARNING",
                    maxDisplays: null,
                    version: null,
                    isClosable: null,
                  },
                },
              },
              {
                label: "Confirm",
                gaLabel: "all products - daily - 80",
                minimizedLabel: null,
                type: "button",
                buttonType: "PRIMARY",
                path: "/api/lossLimits/confirm",
                url: "https://playerprotection.nxt.com.betfair",
                target: "api",
                action: "ACCEPT_OR_CANCEL_LOSS_LIMIT",
                data: '{"productName": "GLOBAL","confirmed": "true"}',
                actionFinalize: {
                  onErrorBanner: {
                    index: 1,
                    bannerInfo: {
                      title: "Sorry, something went wrong",
                      bodyContent: {
                        text: "We were unable to confirm your pending limit. Please try again later.",
                        items: null,
                        formContent: null,
                        contactUsInfo: null,
                      },
                    },
                    minimizedBannerInfo: null,
                    bannerActions: [
                      {
                        label: "Dismiss",
                        gaLabel: null,
                        minimizedLabel: null,
                        type: "button",
                        buttonType: null,
                        path: null,
                        url: null,
                        target: "close",
                        action: null,
                        data: null,
                      },
                    ],
                    isMinimized: null,
                    priority: null,
                    useCase: null,
                    flow: null,
                    template: null,
                    attentionLevel: "WARNING",
                    maxDisplays: null,
                    version: null,
                    isClosable: null,
                  },
                },
              },
            ],
            isMinimized: null,
            priority: "3120",
            useCase: "LOSS_LIMIT",
            flow: "TBD",
            template: null,
            attentionLevel: "WARNING",
            maxDisplays: null,
            version: null,
            isClosable: null,
            bannerType: "rg",
          },
          {
            index: 2,
            bannerInfo: {
              title: "Verify Number",
              bodyContent: {
                text: "Did you know you can enhance the security of your account by verifying your phone number?",
                items: null,
                formContent: null,
                contactUsInfo: null,
              },
            },
            minimizedBannerInfo: {
              bodyText: "Did you know you can enhance the security of your account by verifying your phone number?",
            },
            bannerActions: [
              {
                label: "Verify Number",
                gaLabel: null,
                minimizedLabel: "Verify Number",
                type: "button",
                buttonType: "PRIMARY",
                path: "/accountdetails/mydetails?shouldVerifyPhone=true",
                url: "https://myaccount.nxt.internal:443/accountdetails/mydetails?shouldVerifyPhone=true&flow=tbd",
                target: "_top",
                action: null,
                data: null,
                actionFinalize: {
                  onErrorBanner: null,
                },
              },
            ],
            isMinimized: true,
            priority: "4120",
            useCase: "DEFAULT",
            flow: "TBD",
            template: null,
            attentionLevel: "WARNING",
            maxDisplays: null,
            version: null,
            isClosable: false,
            bannerType: "phone",
          },
        ],
        currentBanner: {
          index: 0,
          bannerInfo: {
            title: "News banner title",
            bodyContent: {
              text: "New banner body text",
              items: null,
              formContent: null,
              contactUsInfo: null,
            },
          },
          minimizedBannerInfo: {
            bodyText: "New banner body text",
          },
          bannerActions: [
            {
              label: "Find out more",
              gaLabel: null,
              minimizedLabel: "Find out more",
              type: "button",
              buttonType: "PRIMARY",
              path: "/myaccount/test",
              url: "https://www.betfair.com/",
              target: "_blank",
              action: null,
              data: null,
              actionFinalize: {
                onErrorBanner: null,
              },
            },
            {
              label: "Dismiss",
              gaLabel: null,
              minimizedLabel: "Dismiss",
              type: "button",
              buttonType: "SECONDARY",
              path: "https://myaccount.nxt.com.betfair/usp/set",
              url: "https://www.betfair.com/",
              target: "api",
              action: "UPDATE_USER_PREFERENCE",
              data: '{"preferenceKey": "maw.news.banner","value":"958"}',
              actionFinalize: {
                onErrorBanner: null,
              },
            },
          ],
          isMinimized: true,
          priority: "2120",
          useCase: "DEFAULT",
          flow: "TBD",
          template: null,
          attentionLevel: "INFO",
          maxDisplays: null,
          version: 958,
          isClosable: null,
          bannerType: "news",
        },
      });
    });
  });
});
