/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fallbackJersey: string;
  firstName: string;
  highlighted: string;
  jersey: string;
  labelDisabled: string;
  lastName: string;
  playerCardContainer: string;
  playerInfoJersey: string;
  playerNameAndPosition: string;
  playerNameContainer: string;
  playerPositionAndNumber: string;
  playerRowInfoContainer: string;
  playerRowStats: string;
  playerStatValue: string;
  playerStatsIcon: string;
  playerStatsIconDisabled: string;
}
export const cssExports: CssExports;
export default cssExports;
