enableStrictSsl: false

httpTimeout: 5000

nmSelfReferences: false

nodeLinker: node-modules

npmRegistryServer: "http://artifactory-prd.prd.betfair/artifactory/api/npm/npm"

npmScopes:
  flutter-global:
    npmRegistryServer: "https://npm.pkg.github.com/Flutter-Global"
    npmPublishRegistry: "https://npm.pkg.github.com/Flutter-Global"
    npmAuthToken: ${GITHUB_TOKEN}

  monterosa-sdk:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/38419920/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: ${MONTEROSA_TOKEN}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'arm64'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'
    - 'gnu'

unsafeHttpWhitelist:
  - artifactory-prd.prd.betfair

yarnPath: .yarn/releases/yarn-3.2.1.cjs
