/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  dark: string;
  default: string;
  label: string;
  light: string;
  lock: string;
  small: string;
  transparent: string;
}
export const cssExports: CssExports;
export default cssExports;
