worker_processes auto;

events {
    worker_connections 1024;
}

http {
   include       /etc/nginx/mime.types;
   default_type  application/octet-stream;

   log_format '$remote_addr $http_x_forwarded_for $remote_user [$time_iso8601] "$request"'
                      '$status $bytes_sent $request_time "$http_referer"'
                      '"$http_user_agent"'
   access_log  /dev/stdout;
   error_log   /dev/stderr warn;

   sendfile on;
   log_not_found on;
   merge_slashes on;

    types_hash_max_size 4096;
    server_names_hash_bucket_size 128;


    gunzip on;
    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain
               text/xml
               text/css
               image/svg+xml
	       image/png
               image/jpeg
               application/octet-stream
               application/xml
               application/xhtml+xml
               application/rss+xml
               application/atom_xml
               application/jsonwelcome
               application/javascript
	       application/json
               application/x-javascript;

    upstream webserver {
    	server 127.0.0.1:9001;
    }

    upstream bff-gql {
    	server 127.0.0.1:8082; # external service
    }

    upstream http-webserver {
    	server 127.0.0.1:8081; # external service
    }

    map $http_host $proxy_host_domain {
        default com;
        .es$ es;
        .it$ it;
        .ro$ ro;
        .br$ bet.br;
    }

    server {
        server_name localhost.betfair.com localhost.betfair.it localhost.betfair.es localhost.betfair.se localhost.betfair.ro localhost.betfair.bg localhost.betfair.bet.br;
        listen 80;
        proxy_buffering on;
        proxy_buffers 128 8k;
        proxy_buffer_size 8k;
        proxy_busy_buffers_size 8k;

        location /health {
          access_log off;
          return 200;
        }

        port_in_redirect off;

        resolver 169.254.169.253;

        include /etc/nginx/conf.d/nginx.locations.conf;
    }
}
