/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottom: string;
  content: string;
  contentText: string;
  contentTextActive: string;
  contentTextFinished: string;
  contentTextIneligible: string;
  contentTextSelected: string;
  contentTextSuspended: string;
  divider: string;
  dynamic: string;
  freezeCard: string;
  freezeCardActive: string;
  freezeCardFinished: string;
  freezeCardIneligible: string;
  freezeCardSelected: string;
  freezeCardSuspended: string;
  icon: string;
  iconActive: string;
  iconFinished: string;
  iconIneligible: string;
  iconSelected: string;
  iconSuspended: string;
  label: string;
  labelActive: string;
  labelFinished: string;
  labelIneligible: string;
  labelSelected: string;
  labelSuspended: string;
  statusLabel: string;
  top: string;
}
export const cssExports: CssExports;
export default cssExports;
