#!/bin/bash

#  generateRawDataFile.sh
#
#   This script generates a raw-data.json file with all the assets from the games-assets repo. A pre generated file can
#   speed up other scripts that need it and also could eliminate the errors generated by large number of assets like
#   timeouts.
#
#  Created by Cosmin Titei on 08/06/2021.
#  Copyright © 2020 PaddyPowerBetfair. All rights reserved.


###### Todo
# 1. Error Handling:
#     - use different error codes for different errors
#     - reuse some codes also for other scripts for the same errors
######
BASEDIR=$(dirname "$0")
FILE_NAME=$(basename "$0")
TEMP_FOLDER="$BASEDIR/../temp"
RAW_DATA_FILE_PATH="$TEMP_FOLDER/raw-data.json"

# Defaults
DEFAULT_NUMBER_OF_RETRIES=3
DEFAULT_LOG_FILE="$TEMP_FOLDER/copyGames.log"

########################################################################################################################
function showHelp() {
    ##### Usage #####
    printf "USAGE:\n  %s [FLAGS]\n\n" "$0"

    ##### Flags #####
    printf "FLAGS:\n"
    printf "  --source              the path to the game assets. \n"
    printf "  --verbose             if present it will print the logs on the screen instead of the %s file \n" "$DEFAULT_LOG_FILE"
    printf "  --help, -h            show help\n"
    printf "\n\n\n"

    ##### Examples #####
    printf "EXAMPLES:\n"

    printf "  0. Showing the help .\n"
    printf "        ./generateRawDataFile.sh -h \n"
    printf "        ./generateRawDataFile.sh --help \n"
    printf "  1. Generate raw-data.json file using a remote bucket as a games assets path.\n"
    printf "        ./generateRawDataFile.sh --source=minio/games-assets-bf \n"
    printf "  2. Generate raw-data.json file using a local folder for games assets path.\n"
    printf "        ./generateRawDataFile.sh --source=/Users/SomeUser/temp/games-assets \n"

    ##### END #####
    printf "\n\n"
}
########################################################################################################################
# Logging function
## add extra param in order to override $VERBOSE flag value
function logMessage() {
    if [[ $VERBOSE == "true" ]] || [[ $3 == "true" ]]; then
        printf "[%s] \t $FILE_NAME \t %s\n" "$(date "+%H:%M:%S")" "$1 $2"
    else
        printf "[%s] \t $FILE_NAME \t %s\n" "$(date "+%H:%M:%S")" "$1 $2" >> "$DEFAULT_LOG_FILE"
    fi
}

# Parse the script input parameters and save them to global variables
function parseArguments() {
    local arg

    for arg in "$@"; do
        local isParamValid=false

        ##### Help
        if [[ "$arg" =~ ^--help$ ]] || [[ "$arg" =~ ^-h$ ]]; then
            isParamValid=true
            showHelp
            exit 0
        fi

        ##### Verbose - if present log to screen instead of a log file
        if [[ "$arg" =~ ^--verbose$ ]] || [[ "$arg" =~ ^-v$ ]]; then
            VERBOSE=true
            isParamValid=true
        fi

        ##### Skip MinIO check
        if [[ "$arg" =~ ^--skip-check$ ]]; then
            SKIP_CHECK=true
            isParamValid=true
        fi

        ##### Assets Source Path - Games Assets Path
        if [[ "$arg" =~ "--source=" ]]; then
            argValue="${arg/--source=/}"
            if [ -n "$argValue" ]; then
                ASSETS_SOURCE_PATH="$argValue"
                isParamValid=true
                SCRIPT_ARGUMENTS+=("$arg")
            fi
        fi

        if [[ "$isParamValid" == "false" ]] && [[ ! $arg == "" ]]; then
            printf '  Script execution stopped: Invalid flag name or flag usage: "%s" \n\n\n' "$arg"
            exit 1
        fi
    done

    logMessage "INFO" "Running $FILE_NAME script. For more options run the script with --help or -h flag"
}

# Validate the script parameters
function validateParamsValues() {
    if [[ -z $ASSETS_SOURCE_PATH ]]; then
        logMessage "ERROR" "Script execution stopped: missing value for --source,-s flag." "true"
        exit 10
    fi
    ASSETS_SOURCE_PATH=$(echo "$ASSETS_SOURCE_PATH" | sed "s/\/$//" ) # remove unwanted trailing /
}

function __printParamValues__() {
    logMessage "INFO" "Running script: $FILE_NAME with the following parameters: $(printf "%s " "${SCRIPT_ARGUMENTS[@]}")"
    logMessage "INFO" "Value for \$BASEDIR: $BASEDIR"
    logMessage "INFO" "----------"
}

# Run all the prerequisites of the csv file generation
function initScript() {
    ##### Parse script arguments #####
    parseArguments "$@"

    ##### Initialize missing required variables with default values #####
    validateParamsValues

    if [[ $VERBOSE == "true" ]]; then
        __printParamValues__
    fi

    ##### Check if the dependencies are installed and configured ok
    if [[ $SKIP_CHECK != "true" ]]; then
        if ! "$BASEDIR"/checkDependencies.sh "$ASSETS_SOURCE_PATH"; then
            exit 1
        fi
    fi

    if ! [[ -d "$TEMP_FOLDER" ]]; then
        mkdir "$TEMP_FOLDER"
    fi
}

# Get data from games asset server as a JSON file
function getRawData() {
    local shouldRetry=true
    local retryNumber=1

    while [ $shouldRetry = true ] && [ $retryNumber -le $DEFAULT_NUMBER_OF_RETRIES ] ; do
        logMessage "INFO" "Get the list of all resources from games assets server. Retry: $retryNumber"
        mc ls --json --recursive "$ASSETS_SOURCE_PATH" | tr "\n" " " | sed "s/} {/},{/g" | sed "s/^{/[{/" | sed "s/} $/}]/" > "$RAW_DATA_FILE_PATH"

        # Check if the retrieved data is valid
        if [[ ! -s "$RAW_DATA_FILE_PATH" ]] ; then
            logMessage "ERROR" "$RAW_DATA_FILE_PATH not found!"
            retryNumber=$(( retryNumber + 1 ))
        else
            rawDataStatus=$(jq 'if .[0].status == "error" then "\(.[0].error.message) \(.[0].error.cause.message)" else "success" end' < "$RAW_DATA_FILE_PATH")
            if [[ "$rawDataStatus" = '"success"' ]] ; then
                logMessage "INFO" "$RAW_DATA_FILE_PATH generated with success"
                shouldRetry=false
            else
                logMessage "ERROR" "$TEMP_FOLDER/raw-data.json generated with errors - $rawDataStatus"
                retryNumber=$(( retryNumber + 1 ))
            fi
        fi

        if [ $shouldRetry = true ] && [ $retryNumber -gt $DEFAULT_NUMBER_OF_RETRIES ] ; then
            logMessage "WARNING" "$RAW_DATA_FILE_PATH couldn't be generated - maximum number of reties reached!"
            exit 1
        fi
    done
}
########################################################################################################################
# Script starts from here
initScript "$@"

if ! getRawData ; then
    logMessage "ERROR" "$RAW_DATA_FILE_PATH file could not be generated!"
    exit 1
fi
