/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  banner: string;
  brandTitle: string;
  content: string;
  default: string;
  iconDefault: string;
  leftIcon: string;
  miniBanner: string;
  rightChevron: string;
  subText: string;
  textDefault: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
