/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButton: string;
  betButtonContainer: string;
  microPlayer: string;
  microPlayerContainer: string;
  outcomesLabel: string;
  placeholderContainer: string;
  statsLabel: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
