version: "3.4"
name: sbg
services:
  bff-gql:
    image: docker.app.betfair/ppb/tbd/bff/bff-gql:local
    environment:
      NODE_OPTIONS: "--inspect=0.0.0.0"
    ports:
      - "9231:9229"
    volumes:
      - ${PWD}/../../bf-tbd-http-bff-gql/config/certificates:/etc/bf-fabric/certificates
      - ${PWD}/../../bf-tbd-http-bff-gql/config/bff-gql-http-sbg-qa.json:/etc/bf-fabric/bff-gql-http.json
      - ${PWD}/../../bf-tbd-http-bff-gql/src/config:/app/dist/config
  reverseproxy:
    image: ppb/tbdbf/dev/reverseproxy-local
    build:
      context: ${PWD}/../reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/../reverse-proxy/dev/environment.json:/usr/share/nginx/app.environment.json
