/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonContainer: string;
  card: string;
  durationContainer: string;
  footer: string;
  header: string;
  linkContainer: string;
  marketContent: string;
  marketContentContainer: string;
  marketSection: string;
  outcomesContainer: string;
  scoreContainer: string;
  seeAllContainer: string;
  statsContainer: string;
  statsPlaceholderContainer: string;
  teamContainer: string;
  teamsRow: string;
}
export const cssExports: CssExports;
export default cssExports;
