/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  obbEnhancedTrackingContainer: string;
  playerNameStyle: string;
  playerProgressTitle: string;
  statsListTrackingContainer: string;
  statsListTrackingLineContainer: string;
  trackingBarContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
