/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonsContainer: string;
  container: string;
  description: string;
  screenshotFrame: string;
  screenshotOverlay: string;
}
export const cssExports: CssExports;
export default cssExports;
