worker_processes auto;

events {
    worker_connections 1024;
}

http {
   include       /etc/nginx/mime.types;
   default_type  application/octet-stream;

   access_log  /var/log/nginx/tbd-access.log;
   error_log   /var/log/nginx/tbd-error.log error;

   sendfile on;
   log_not_found on;
   merge_slashes on;

    types_hash_max_size 4096;
    server_names_hash_bucket_size 128;

    resolver 127.0.0.11 ipv6=off;

    gunzip on;
    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain
               text/xml
               text/css
               image/svg+xml
	       image/png
               image/jpeg
               application/octet-stream
               application/xml
               application/xhtml+xml
               application/rss+xml
               application/atom_xml
               application/jsonwelcome
               application/javascript
	       application/json
               application/x-javascript;

    map $http_host $proxy_host_domain {
        default com;
        nxt\.com\.betfair$ com.nxt.ppbdev.com;
        nxt\.es\.betfair$ es.nxt.ppbdev.com;
        nxt\.it\.betfair$ it.nxt.ppbdev.com;
        nxt\.bet\.br\.betfair$ bet.br.nxt.ppbdev.com;
        qa\.es\.betfair$ es;
        qa\.it\.betfair$ it;
        qa\.bet\.br\.betfair$ bet.br;
    }

    server {
        server_name localhost.betfair.com localhost.betfair.it localhost.betfair.es localhost.betfair.se localhost.betfair.ro localhost.betfair.bg localhost.betfair.bet.br;
        listen 80;
        listen *:443 ssl;
        http2 on;
        proxy_buffering on;
        proxy_buffers 128 8k;
        proxy_buffer_size 8k;
        proxy_busy_buffers_size 8k;

        ssl_certificate /etc/nginx/ssl-cert/localhost.betfair.com-cert.pem;
        ssl_certificate_key /etc/nginx/ssl-cert/localhost.betfair.com-key.pem;

        port_in_redirect off;

        include /etc/nginx/conf.d/custom.locations.conf;
        include /etc/nginx/conf.d/locations.conf;
    }

    include /etc/nginx/conf.d/*.upstream;
}
