/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  awayContainer: string;
  caption: string;
  container: string;
  homeContainer: string;
  resultContainer: string;
  resultsContainer: string;
  scoresContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
