/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  aggregatorBody: string;
  card: string;
  container: string;
  dividerContainer: string;
  legCardGroup: string;
  legGroupContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
