/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bettingOpportunitiesContainer: string;
  buttonContainer: string;
  card: string;
  footer: string;
  linkContainer: string;
  marketContent: string;
  marketContentContainer: string;
  marketSection: string;
  popularEvidenceContainer: string;
  popularEvidencePlaceholderContainer: string;
  showMoreContainer: string;
  statsContainer: string;
  statsPlaceholderContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
