/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  blue: string;
  content: string;
  header: string;
  inlinePanel: string;
  pink: string;
  title: string;
  titleContainer: string;
  titlePrefix: string;
}
export const cssExports: CssExports;
export default cssExports;
