/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  emptyState: string;
  emptyStateImage: string;
  emptyStateTransactionLink: string;
  headerActionContainer: string;
  headerBetsToggleContainer: string;
  myBetsHeaderContainer: string;
  myBetsPageContainer: string;
  swimlane: string;
  transactionHistory: string;
}
export const cssExports: CssExports;
export default cssExports;
