/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  carouselArrow: string;
  carouselArrowLeft: string;
  carouselArrowRight: string;
  carouselContainer: string;
  container: string;
  editSquadButtonIcon: string;
  lastPlayer: string;
  microPlayerContainer: string;
  microPlayersCarousel: string;
  playerCarouselClickable: string;
}
export const cssExports: CssExports;
export default cssExports;
