/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  attribute: string;
  jockey: string;
  runner: string;
  runnerAttribute: string;
  runnerAttributeLabel: string;
  runnerContainer: string;
  runnerInfo: string;
  silk: string;
  silkDefault: string;
}
export const cssExports: CssExports;
export default cssExports;
