/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  competitionByCountry: string;
  drawerContentWithPadding: string;
  listPadding: string;
  placeholder: string;
  placeholderContainer: string;
  sectionTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
