/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  column: string;
  columnStats: string;
  columnText: string;
  columns: string;
  competitionHeader: string;
  title: string;
  titleLink: string;
}
export const cssExports: CssExports;
export default cssExports;
