/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonColumnContainer: string;
  exchangeButtonsContainer: string;
  horseRacingRunner: string;
  marketDepthButtonsContainer: string;
  nonRunnerContainer: string;
  racingRunner: string;
  runner: string;
  runnerBase: string;
  spacingDiv: string;
}
export const cssExports: CssExports;
export default cssExports;
