/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bannersContainer: string;
  connectedUserProfileOverlay: string;
  connectedUserProfileOverlayDesktop: string;
  connectedUserProfileOverlaySlideDown: string;
  settingsView: string;
  userProfileIframe: string;
}
export const cssExports: CssExports;
export default cssExports;
