/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButtonWrapper: string;
  correctScoreCard: string;
  correctScoreRunnerColumn: string;
  correctScoreRunnerLine: string;
  correctScoreRunnerList: string;
  marketHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
