/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  icon: string;
  marketDetailsContainer: string;
  matchStatSelectionCardContainer: string;
  subtitle: string;
  title: string;
  titleContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
