location ~ /api/tbd/bff-gql/(.*)$ {
  # to be fixed - path should be api/tdbsbg
    proxy_pass http://apitbdsbg/api/tbd/bff-gql/$1$is_args$args;
    proxy_method POST;
    proxy_set_header Host $host;
    proxy_pass_request_headers on;
    proxy_set_header Origin "www.skybet.com";
}
