import { ApolloNormalizers, normalizers, Normalizers } from "./normalizer-config";
import {
  getNormalizableObjectsFromPartial,
  isNormalizable,
  isNormalizablePartial,
  isObjectWithTypename,
  isValidTypename,
  isPartial,
  isObject,
  isFragmentMinimal,
  isFragmentWithEdges,
  isApolloMigratedCard,
} from "./normalizer-helpers";

// A map with [__typename]: "normalizer output"
export type NormalizersResult = {
  [Key in keyof Normalizers]?: ReturnType<Normalizers[Key]>["data"][];
};

// A map with [__typename]: "apollo normalizer output"
export type ApolloNormalizersResult = {
  [Key in keyof ApolloNormalizers]?: ReturnType<ApolloNormalizers[Key]>["data"][];
};

/**
 * Normalizer responsible to take an entry point (e.g. View) and map every layout into an object
 * that will be consumed by our reducers
 *
 * @param fragment The query frament (type generated by compile-graphql)
 * @param base An object to be recursively mutated
 */
export function normalizerEngine(
  fragment: Record<string, unknown> | unknown[],
  base?: NormalizersResult,
): NormalizersResult {
  const result = base || {};

  if (isObject(fragment)) {
    let typename: string | null = null;

    if (isObjectWithTypename(fragment)) {
      typename = fragment.__typename;
    }

    // @ts-expect-error We need to ignore this. The Normalizers type is a really big object and
    // the type inference here needs more than 4GB of memory just to typecheck
    const normalizer = normalizers[typename] || null;

    if (normalizer && typename && isValidTypename(typename)) {
      if (isFragmentMinimal(fragment)) {
        if (!result[typename]) {
          result[typename] = [];
        }

        // With the migration to Apollo, some fragments are not valid anymore.
        // This is a temporary solution to avoid the app to crash.
        try {
          result[typename]?.push(normalizer(fragment).data);
        } catch {
          console.warn("Failed to normalize fragment", fragment);
        }
      }
    }

    // Cards migrated to apollo have their own query fragments that do not match our store application state type definition
    // Therefore we have no garantee that normalization of those cards to the store will end up in a valid state
    if (typename && isApolloMigratedCard(typename)) {
      return result;
    }

    // Iterate over all props that are inner objects and
    // call the normalizer for each one of them
    Object.keys(fragment).forEach((key) => {
      const innerFragment = fragment[key];

      if (!isNormalizable(innerFragment)) {
        return;
      }

      // We need to ignore partials and partialItems manually. No better solution so far.
      // Some partials are normalizable, to improve perceived performance on UI. Those are identified by isNormalizablePartial
      if (isPartial(key)) {
        if (!isFragmentWithEdges(innerFragment)) {
          return;
        }

        if (isNormalizablePartial(innerFragment)) {
          normalizerEngine(innerFragment, result);
          return;
        }

        getNormalizableObjectsFromPartial(innerFragment).forEach((object) => {
          normalizerEngine(object, result);
        });

        return;
      }

      normalizerEngine(innerFragment, result);
    });
  } else if (Array.isArray(fragment)) {
    fragment.forEach((innerFragment) => {
      if (isNormalizable(innerFragment)) {
        normalizerEngine(innerFragment, result);
      }
    });
  }

  return result;
}
