/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  description: string;
  icon: string;
  iframe: string;
  iframeWrap: string;
  links: string;
  title: string;
  twitterTitle: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
