/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  arrow: string;
  flexEnd: string;
  image: string;
  raceViewLinkCard: string;
  space: string;
  subTitleContainer: string;
  subtitleLabel: string;
  title: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
