/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  freebets: string;
  input: string;
  inputsContainer: string;
  notifications: string;
  placeButton: string;
  quickStakes: string;
}
export const cssExports: CssExports;
export default cssExports;
