/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  byTimeRangeMeeting: string;
  circle: string;
  decoratedGame: string;
  emptyStateInstruction: string;
  emptyStateMessage: string;
  favouritesTitle: string;
  favouritesWelcome: string;
  game: string;
  gameTileWidgetPositioning: string;
  gameTileWidgetPositioningAfterBetslipOpen: string;
  gamingLink: string;
  gamingRibbonCardGroup: string;
  heartIcon: string;
  highlightedSelection: string;
  navigation: string;
  pinnedRibbonCardGroup: string;
  promotion: string;
  roundGame: string;
  segmentedContainer: string;
  segmentedTitle: string;
  segmentedWrapper: string;
  snap: string;
  sportviewlink: string;
  supportingContent: string;
  swimlaneItemContainer: string;
  xmallGameTile: string;
}
export const cssExports: CssExports;
export default cssExports;
