/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  away: string;
  card: string;
  home: string;
  playerName: string;
  sideDescription: string;
  sideTitle: string;
  substitution: string;
}
export const cssExports: CssExports;
export default cssExports;
