/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButton: string;
  blueBg: string;
  darkBlueBg: string;
  darkGreyBg: string;
  darkPinkBg: string;
  fadeOut: string;
  greyBg: string;
  horizontalBetButton: string;
  icon: string;
  isSelected: string;
  lineThrough: string;
  pinkBg: string;
  primaryLabel: string;
  secondaryLabel: string;
  secondaryLabelContainer: string;
  secondaryLabelHandicap: string;
  tealBg: string;
  twoLinesMax: string;
  yellow700: string;
}
export const cssExports: CssExports;
export default cssExports;
