/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  children: string;
  container: string;
  description: string;
  dot: string;
  entryText: string;
  iconAndTitleContainer: string;
  iconContainer: string;
  infoContainer: string;
  last: string;
  line: string;
  lineContainer: string;
  regularText: string;
  subDescription: string;
  textContainer: string;
  titleContainer: string;
  titleText: string;
  titleWithIconText: string;
}
export const cssExports: CssExports;
export default cssExports;
