export const BETSLIP_LEVEL_NOTIFICATIONS_BLOCKLIST = ["BET_PLACEMENT_FAILURE"];

export const BET_LEVEL_NOTIFICATIONS_BLOCKLIST = [
  "BET_PLACEMENT_RUNNER_FAILURE",
  "OTHER_FAILURE_IN_REQUEST",
  "SUCCESS",
];

export const LEG_LEVEL_NOTIFICATIONS_BLOCKLIST = ["REQUESTED_PRICE_NOT_AVAILABLE", "SUCCESS"];

export const SUSPENDED_FAILURE_CODES = ["EVENT_SUSPENDED", "OUTCOME_DEFINITION_SUSPENDED"];

export const ERRORS_TRIGGERING_QUOTES_UPDATE = ["REQUESTED_PRICE_NOT_AVAILABLE"];

export const IMPLY_BETS_FAILURES_BLOCKLIST = ["GENERAL_FAILURE", "SUCCESS"];

export const QUOTES_FAILURES_BLOCKLIST = ["GENERAL_FAILURE"];

export const PLACE_BETS_FAILURES_BLOCKLIST = [];

export const COMBINED_LEGS_FAILURES_BLOCKLIST = ["IMPOSSIBLE_OBB_CHOICE"];
