/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButtonsContainer: string;
  container: string;
  header: string;
  headerWrapper: string;
  icon: string;
  microPlayerContainer: string;
  microPlayerContainerSquadBet: string;
  squadsContainer: string;
  textContainer: string;
  title: string;
  vsContainer: string;
  vsText: string;
}
export const cssExports: CssExports;
export default cssExports;
