FROM docker.app.betfair/tbd-ci/bookworm-slim-fabric-base-image:master

ARG GITHUB_TOKEN
ARG MONTEROSA_TOKEN
ARG BRAND
ARG ENVIRONMENT
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ENV MONTEROSA_TOKEN=$MONTEROSA_TOKEN

USER root
RUN mkdir -p /var/app/tbd/apps/tbd-http-webserver
RUN chown -R node:node /var/app/tbd

# set user as node (avoid using root) and set global npm configs
USER node
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
ENV NODE_OPTIONS=--max_old_space_size=3072

# working over the monorepo outside the fabric deploy path, mimicking app deploy paths
WORKDIR /var/app/tbd

# install node deps
COPY --chown=node:node .yarn ./.yarn
COPY --chown=node:node package.json yarn.lock .yarnrc.yml .yarnrc.yml ./
COPY --chown=node:node apps/tbd-http-webserver/package.json ./apps/tbd-http-webserver/
COPY --chown=node:node apps/tbd-http-webserver/.npmrc ./apps/tbd-http-webserver/
COPY --chown=node:node apps/tbd-http-webserver/.yalc ./apps/tbd-http-webserver/.yalc
COPY --chown=node:node packages/tbd-store/.yal[c] packages/tbd-store/.yalc
COPY --chown=node:node packages/tbd-store/package.json packages/tbd-store/

RUN yarn workspaces focus \
  @ppb/tbd-http-webserver \
  @ppb/tbd-store

# when running only this strand, replaces manifest usually generated by webpack
COPY ./apps/tbd-http-webserver/metadata/fake-manifest.json /var/tmp/webserver/tbd-assets/manifest.json

# define "rebuild" script to be run by nodemon
RUN echo 'cd deploy/tbd-http-webserver; npx tsc -b && sh build.dev.sh' > /var/app/tbd/apps/tbd-http-webserver/rebuild.sh

# copy source files and build strand
COPY --chown=node:node packages/tbd-store/ packages/tbd-store/

COPY apps/tbd-http-webserver/config ${FABRIC_CONFIG_PATH}/

COPY apps/tbd-http-webserver/build.sh apps/tbd-http-webserver/
COPY apps/tbd-http-webserver/build.dev.sh apps/tbd-http-webserver/
COPY apps/tbd-http-webserver/tsconfig.json apps/tbd-http-webserver/
COPY apps/tbd-http-webserver/lib/ apps/tbd-http-webserver/lib/

# These ENV files are parameterized for use with BF or SBG env files
COPY apps/tbd-http-webserver/lib/config/env-templates/environment-${BRAND}.${ENVIRONMENT}.json apps/tbd-http-webserver/lib/config/environment.json
COPY apps/tbd-http-webserver/lib/config/env-templates/environment-${BRAND}-backend.json apps/tbd-http-webserver/lib/config/environment-backend.json

WORKDIR /var/app/tbd/apps/tbd-http-webserver/

RUN yarn build

# Symlinks the strand content to fabric path leaving out all repo packages "behind".
# The strand paths become less verbose by removing the repo "apps/tbd-http-webserver" internal path for all
# configurations an compose files.
RUN ln -s /var/app/tbd/apps/tbd-http-webserver ${FABRIC_STRANDS_PATH}

WORKDIR ${FABRIC_PATH}

# The port the application listens to
EXPOSE 8081

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["node", "--enable-experimental-regexp-engine-on-excessive-backtracks", "--", "bin/fabric.js", "run", "/etc/bf-fabric/config-http.json"]
