%define version 1.4.0
%define majorversion 1
%define strandname bf-tbd-http-webserver-v%{majorversion}
%define stranddir %{buildroot}%{_localstatedir}/app/bf-fabric/deploy/%{strandname}
%define release %{_buildnumber}

Name:       %{strandname}
Version:    %{version}
Release:    %{release}
Summary:    bf-tbd-http-webserver
Group:      Software
Vendor:     Rebuild
License:    SEE LICENSE IN https://developer.betfair.com/1
URL:        https://github.com/Flutter-Global/tbd/tree/master/apps/tbd-http-webserver
Provides:   %{strandname}
BuildArch:  x86_64
BuildRoot:  %{_topdir}/BUILDROOT

%description
bf-tbd-http-webserver strand

%build

%install
mkdir -p %{stranddir}
cp -r %{_sourcedir}/* %{stranddir}

# remove redirect-urls.json to be replaced by the one generated by Chef cookbooks
rm %{stranddir}/lib/config/redirect-urls.json

# Remove dev environmnet.json configuration
rm %{stranddir}/lib/config/environment.json

# Create /tmp/webserver/tbd-assets/ folder where manifest.json should be stored
mkdir -p %{buildroot}%{_localstatedir}/tmp/webserver/tbd-assets/

%files

%attr(0755,nodejs,root) %{_localstatedir}/app/bf-fabric/deploy/%{strandname}
%attr(0755,nodejs,root) %{_localstatedir}/tmp/webserver
