// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  brand: string;
  exchange: string;
  games: string;
  logoContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
