/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  extraTime: string;
  left: string;
  penalties: string;
  recentFormCompetition: string;
  recentFormContainer: string;
  recentFormDate: string;
  recentFormIconContainer: string;
  recentFormOpponent: string;
  recentFormScore: string;
  recentFormScorePenalties: string;
  right: string;
}
export const cssExports: CssExports;
export default cssExports;
