/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  header: string;
  loadingLabel: string;
  playerInfo: string;
  playerName: string;
  playerPosition: string;
  playerShirtNumber: string;
}
export const cssExports: CssExports;
export default cssExports;
