# Ignore everything
**

# Allowed files and directories
!packages/**
!.yarn
!.yarnrc.yml
!yarn.lock
!package.json
!apps/pp/web/**
!tools/**
!babel.config.js
!.browserslistrc
!pql-manifest*

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/node_modules/
**/dist
**/regression-tests
