version: "3.4"
services:
  reverseproxy:
    image: ppb/tbdpp/dev/reverseproxy-qacms
    build:
      context: ${PWD}/../reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/../reverse-proxy/dev/webapp.d/qacms.apitbd-remote.locations.conf:/etc/nginx/conf.d/custom.locations.conf
      - ${PWD}/../reverse-proxy/dev/webapp.d/qa.locations.conf:/etc/nginx/conf.d/locations.conf
      - ${PWD}/../reverse-proxy/dev/webapp.d/qacms.upstream:/etc/nginx/conf.d/qacms.upstream
    depends_on:
      - http-webserver
      - webserver
volumes:
  tbd-assets:
