/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betslipContainer: string;
  betslipContainerDesktop: string;
  betslipContentWrapper: string;
  closeButton: string;
  headerContentDesktop: string;
  headerDesktop: string;
  inputDesktopWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
