// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  externalContent: string;
  settingsContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
