/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  collapseHeader: string;
  collapseWrapper: string;
  container: string;
  noStatsLabel: string;
  placeholder: string;
  statItem: string;
  statLabel: string;
  statTitle: string;
  statValue: string;
  stats: string;
}
export const cssExports: CssExports;
export default cssExports;
