/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  extraContent: string;
  header: string;
  hint: string;
  infoContainer: string;
  option: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
