import { Middleware } from "redux";

import { ApplicationState } from "../state";
import {
  getAutoConfirmSportsbookBetClickEvent,
  getBetReceiptCopyToClipboardEvent,
  getBetReceiptSuccessMessageSawEvent,
  getBetReceiptToggleClickEvent,
  getBetslipAccordionHeaderClickEvent,
  getBetslipSportsbookTabSwitchEvent,
  getConfirmSportsbookBetClickEvent,
  getEditSportsbookBetClickEvent,
  getBetslipDeeplinkEvent,
  getBetslipHeaderClickEvent,
  getBetslipSportsbookMultipleBetTypeClickEvent,
  getChangePersistenceTypeClickEvent,
  getExchangeAutoConfirmedBetClickEvent,
  getExchangeConfirmBetClickEvent,
  getExchangePriceChangeEvent,
  getFilterApplyEvent,
  getFilterCloseEvent,
  getFilterOpenEvent,
  getFilterResetClickEvent,
  getLoadedNotFoundView,
  getLogoutClickEvent,
  getMyAccountMenuToggleEvent,
  getMyBetsBetSharingDismissEvent,
  getMyBetsBetSharingPreviewEvent,
  getMyBetsBetSharingShareBetEvent,
  getMyBetsBetSharingShareImageEvent,
  getMyBetsAccaFreezeOpenedEvent,
  getMyBetsAccaFreezeClosedEvent,
  getBetMutationAccaFreezeSelectedEvent,
  getBetMutationAccaFreezeDeselectedEvent,
  getMyBetsCancelAllEvent,
  getMyBetsCopyBetIdToClipboardEvent,
  getMyBetsCopyDeviceIdToClipboardEvent,
  getMyBetsEditBottomSheetCloseEvent,
  getMyBetsExchangeOrderStatusClickEvent,
  getOpenPersistenceTypeMenuEvent,
  getPlaceExchangeBetClickEvent,
  getPlaceSportsbookBetClickEvent,
  getSbkIncrementStakeEvent,
  getExcIncrementSizeEvent,
  getBetslipSbkDepositToConfirmBetClickEvent,
  getBetslipSbkDepositToPlaceBetClickEvent,
  getBetslipSbkRemoveAllEvent,
  getBetslipSbkReAddSelectionsEvent,
  getBetslipSbkNotificationShownEvent,
  getBetslipObbNotificationShownEvent,
  getMarketRulesToggleModalEvent,
  getToggleMarketGraphEvent,
  getToggleRecentRacesEvent,
  getMarketGraphSelectViewEvent,
  getMarketGraphSelectGraphEvent,
  getMarketDepthClickEvent,
  getPebbleSelectionClickEvent,
  getSearchCancelClickEvent,
  getSearchClearClickEvent,
  getToggleExpandableCardGroupEvent,
  getToggleRunnerInfoEvent,
  getBetReceiptExchangeDoneClickEvent,
  getSearchTabClickEvent,
  getSearchBarFocusEvent,
  getPNInteractionClickEvent,
  getMyBetsSinglesBellClickEvent,
  getMyBetsMultiplesBellClickEvent,
  getMyBetsSaveClickEvent,
  getSawCardEvent,
  getSwitchProductEvent,
  getOpenPredictsEvent,
  getToggleShowMoreEvent,
  getStatisticsModalToggleEvent,
  getStatisticsItemClickEvent,
  getNextRacesRaceFilterClickEvent,
  getMarketSnackBarClosedEvent,
  getMarketSnackBarSuspendedEvent,
  getAzSwitchToggleEvent,
  getMyBetsOrderTypeFilterClickEvent,
  getPromoDescriptionToggleEvent,
  getToggleAccordionEvent,
  getRaceReplaysToggleEvent,
  getMaxPayoutAcceptMessageClickEvent,
  getBetslipBonusActivationEvent,
  getContentSummaryCollapseEvent,
  getNextRacesRaceClickEvent,
  getBroadcastsToggleEvent,
  getBroadcastsAndStatisticsToggleEvent,
  getTimeFormBroadCastsToggleEvent,
  getBetslipEachWayToggleEvent,
  getBetslipAccaInsuranceToggleEvent,
  getBetslipMyOddsBoostToggleEvent,
  getBetslipCastBetChangeEvent,
  getBetslipCastBetOrderChangeEvent,
  getSwitcherEvent,
  getNavigationTabClickEvent,
  getToggleTimeFormEvent,
  getOpenBetslipEvent,
  getGenerosityWalletClick,
  getGenerosityWalletCloseEvent,
  getFreeBetsWalletToggleEvent,
  getObbSelectionsEvents,
  getHeritageToggleClickEvent,
  getOpenClearBetslipEvent,
  getRefuseConfirmationEvent,
  getAcceptConfirmationEvent,
  getGenerosityWalletBetslipClickAction,
  getGamingSearchBarFocusEvent,
  getGamingSearchCancelClickEvent,
  getGamingSearchHistoryPebbleClickEvent,
  getGamingSearchResults,
  getGamingSearchClearClickEvent,
  getHamburgerMenuOpenEvent,
  getHamburgerMenuCloseEvent,
  getBetMutationAccaFreezeConfirmEvent,
  getMyBetsHeaderTooltipToggleEvent,
  getEditSquadOpenEvent,
  getClosePlayerPickerModalEvent,
  getSquadBetPlayerPickerToggleSquadParticipantEvent,
  getSquadBetPlayerPickerRemoveSquadParticipantEvent,
  getSquadBetPlayerPickerBetButtonClickEvent,
  getMyBetsReAddSelectionsEvent,
  getObbEnhancedPlayerCounterEvent,
  getGenerosityWalletPebbleClickEvent,
  getRemoveGenerosityWalletEvent,
  getGenerosityWalletApplyButtonClickEvent,
  getFavouriteMarketsLimitReachedMessageCloseEvent,
  getFavouriteMarketsToggleFavouriteEvent,
  getFavouriteMarketsTooltipCloseEvent,
  getToggleSquadVsSquadPlayersTooltipEvent,
  getObbSectionToggledEvent,
  getObbLayoutToggledEvent,
  getObbShowMoreClickedEvent,
  getBetslipSliderInteractionEvent,
  getBetslipSliderDisplayedEvent,
  getExchangeMyBetsEditClickEvent,
  getMyBetsNotificationsCloseEvent,
  getSportsFilterClickEvent,
  getSearchHistoryClickEvent,
  getEventPageNotificationsToggleEvent,
  getObbEventPopularsShowMoreEvent,
  getObbOnboardingCardsCardGroupDisplayedEvent,
  getObbOnboardingCardsCardGroupSwipeEvent,
} from "./ga4-tagging-resolvers/interface";
import {
  getBottomBarClickEvent,
  getBetslipBetBuilderNavigateToEvent,
  getCompetitionLinkClickEvent,
  getCouponViewCardClickEvent,
  getLinkClickEvent,
  getMarketRulesLinkClickEvent,
  getMoreInfoPlayNewClickEvent,
  getMyAccountMenuLinkEvent,
  getMyAccountQuickLinkEvent,
  getMarketBlurbFAQEvent,
  getNavigateFromNotFoundView,
  getNavigateToEvent,
  getNavigateToEventFromSportEvent,
  getNavigateToGameCategoryEvent,
  getNavigateToGameInfoEvent,
  getNavigationSeeAllPromotionsEvent,
  getPlayNowPlayNewClickEvent,
  getSeeAllLinkClickEvent,
  getNavigateToMarketViewEvent,
  getNavigateToView,
  getRaceViewLinksLinkClickEvent,
  getSearchAzLinkClickEvent,
  getLogoClickEvent,
  getNavigateToSwitcherOptionClickEvent,
  getAllCompetitionsLinkClickEvent,
  getAllMarketsLinkClickEvent,
  getBetslipSbkMaxPayoutNotificationUrlClickEvent,
  getBottomBarPushEvent,
  getQuickLinkClickEvent,
  getViewAllTapEvent,
  getViewFromFavouritesClickEvent,
  getPopularBetBuildNavigateToEventBetBuild,
  getGenerosityWalletHelpClickEvent,
  getHeritageInfoLabelClickEvent,
  getMarketBlurbLinkClickEvent,
  getGenerosityPageNavigation,
  getObbCreatedBetsLinkClickEvent,
  getSettlementLinkNavigation,
  getNavigateToEventFromPlayerPage,
} from "./ga4-tagging-resolvers/navigation";
import { getSearchLinkClickEvent } from "./ga4-tagging-resolvers/click-search-results";
import {
  getJackpotMerchandiseViewEvent,
  getLoadedPageContentEvent,
  getLoadPlayNewEvent,
  getAddGameToFavouritesEvent,
  getRemoveGameFromFavouritesEvent,
} from "./ga4-tagging-resolvers/game-interactions";
import {
  getGameLaunchFromGameInfoEvent,
  getGameLaunchFromPNEvent,
  getGameTileClickEvent,
  getGameLaunchFromBottomBar,
  getGameLaunchFromPromoEvent,
  getGameLaunchFromWidgetEvent,
} from "./ga4-tagging-resolvers/game-launch";
import {
  getExchangeFailedPlaceBetEvent,
  getUpdateBetFailureEvent,
  getSportsbookFailedPlaceBetEvent,
  getObbFailedPlaceBetEvent,
} from "./ga4-tagging-resolvers/bet-placed-fail";
import { getMyAccountEyeIconEvent, getMyAccountToggleCashBalancesViewEvent } from "./ga4-tagging-resolvers/account";
import { ActionTaggingMapper, ActionTypes, TaggingBuilder } from "./ga4-tagging-resolvers/Tagging.types";
import { URL__BETSLIP_DEEPLINK } from "../actions/commands";
import {
  NETWORK__MY_BETS_CANCEL_ALL_UNMATCHED_EXC_BETS_FAILURE,
  NETWORK__MY_BETS_CANCEL_ALL_UNMATCHED_EXC_BETS_SUCCESS,
  NETWORK__MY_BETS_CANCEL_UNMATCHED_EXC_BETS_FAILURE,
  NETWORK__MY_BETS_CANCEL_UNMATCHED_EXC_BET_SUCCESS,
  UI__MY_BETS_BET_SHARING_DISMISS_TAP,
  UI__MY_BETS_BET_SHARING_PREVIEW_TAP,
  UI__MY_BETS_BET_SHARING_SHARE_BET_TAP,
  UI__MY_BETS_BET_SHARING_SHARE_IMAGE_TAP,
  UI__MY_BETS_ACCA_FREEZE_OPENED,
  UI__MY_BETS_ACCA_FREEZE_CLOSED,
  UI__MY_BETS_CANCEL_ALL_UNMATCHED_PRESS,
  UI__MY_BETS_EXC_EDIT_BET_CLOSE,
  UI__MY_BETS_EXC_EDIT_BET_PRESS,
  UI__MY_BETS_EXC_ORDER_STATUS_SWITCH,
  UI__MY_BETS_COPY_BET_ID,
  UI__MY_BETS_COPY_REGULATOR_BET_ID,
  UI__MY_BETS_COPY_DEVICE_ID,
  UI__MY_BETS_ON_ACCORDION_TOGGLE,
  UI__MY_BETS_ORDER_TYPE_FILTER_CLICK,
  UI__MY_BETS_HERITAGE_TOGGLE_FILTER_CLICK,
  UI__MY_BETS_HERITAGE_INFO_LABEL_CLICK,
  UI__MY_BETS_HEADER_TOOLTIP_TOGGLE,
  UI__MY_BETS_SBK_ADD_PREVIOUS_SELECTIONS_CLICK,
} from "../actions/my-bets";
import {
  UI__BET_MUTATION_ACCA_FREEZE_SELECTED,
  UI__BET_MUTATION_ACCA_FREEZE_DESELECTED,
  NETWORK__FREEZE_BET,
} from "../actions/bet-mutation";
import {
  UI__BOTTOM_BAR_CLICK,
  UI__CLICK_ALLMARKETS_LINK,
  UI__FOOTER_LINK_CLICK,
  UI__LAUNCH_GAME,
  UI__LAUNCH_GAME_FROM_GAME_INFO,
  UI__LAUNCH_GAME_FROM_PROMO,
  UI__NAVIGATE_FROM_NOT_FOUND_VIEW,
  UI__NAVIGATE_TO_COMPETITION_VIEW,
  UI__NAVIGATE_TO_DISCOUNT_RATE_EXPLAINED,
  UI__NAVIGATE_TO_EVENT_FROM_COUPON_PRIMARY_MARKET,
  UI__NAVIGATE_TO_EVENT_FROM_SPORT,
  UI__NAVIGATE_TO_GAME_INFO_VIEW,
  UI__NAVIGATE_TO_GAMING_CATEGORY_USING_CATEGORY_LINK_CARD,
  UI__NAVIGATE_TO_GAMING_CATEGORY_USING_SEE_ALL_BUTTON,
  UI__NAVIGATE_TO_FAQ_PAGE,
  UI__NAVIGATE_TO_SEE_ALL_PROMOTIONS,
  UI__NOT_FOUND_VIEW_LOADED,
  UI__PLAY_NEW_LOADED,
  UI__PLAY_NEW_MORE_INFO_BUTTON_CLICK,
  UI__PLAY_NEW_PLAY_NOW_BUTTON_CLICK,
  UI__TAP_ALL_COMPETITIONS_LINK,
  UI__LOGO_CLICK,
  UI__NAVIGATE_TO_SWITCHER_OPTION_CLICK,
  UI__NAVIGATE_TO_MARKET_VIEW,
  UI__NAVIGATE_TO_VIEW,
  UI__NAVIGATE_TO_EVENT_FROM_BETSLIP_PP_BET_BUILDER,
  UI__QUICK_LINK_CLICK,
  UI__NAVIGATE_FROM_CONTENT_SUMMARY_VIEW_LINK,
  UI__RACE_VIEW_LINKS_LINK_CLICK,
  UI__BACK_BUTTON_CLICK,
  UI__CARDGROUP_VIEW_ALL_LINK_TAP,
  UI_NAVIGATE_VIEW_FROM_FAVOURITES,
  UI__NAVIGATE_TO_BET_BUILDER_EVENT_FROM_PP_BET_BUILDER,
  UI__NAVIGATE_GENEROSITY_WALLET_HELP,
  UI__NAVIGATE_GENEROSITY_PAGE,
  UI__MARKET_BLURB_LINK_CLICK,
  UI__LAUNCH_GAME_FROM_PN,
  UI__LAUNCH_GAME_FROM_WIDGET,
  UI__OBB_CREATED_BETS_LINK_CLICKED,
  UI__NAVIGATE_SETTLEMENTLINK,
  UI__NAVIGATE_TO_EVENT_FROM_MARKET_SCOREBOARD,
} from "../actions/navigation";
import { UI__BOTTOM_BAR_GAME_LAUNCH } from "../actions/game-launch";
import {
  PN_INTERACTION_EVENT,
  PN_PARTIAL_SUBSCRIBE_EVENTS_SUCCESS,
  PN_SUBSCRIBE_EVENTS,
  PN_SUBSCRIBE_EVENTS_SUCCESS,
  PN_UNSUBSCRIBE_EVENTS,
  PN_UNSUPPORTED_SUBSCRIBE_EVENTS_SUCCESS,
  PN_MYBETS_SINGLES_BELL_CLICK,
  PN_MYBETS_MULTIPLES_BELL_CLICK,
  PN_MYBETS_NOTIFICATIONS_CLOSE,
  PN_MYBETS_SAVE_CLICK,
  PN_EVENT_PAGE_NOTIFICATIONS_TOGGLE,
} from "../actions/push-notifications";
import {
  UI__CLICK_MARKET_GRAPH_MODE_SELECTOR,
  UI__CLICK_MARKET_GRAPH_TAB_VIEW_SELECTOR,
  UI__CLICK_PEBBLE_ITEM,
  UI__GRAPH_TOGGLE,
  UI__MARKET_RULES_MODAL_TOGGLE,
  UI__MY_ACCOUNT_ICON_CLICK,
  UI__RECENT_RACE_TOGGLE,
  UI__USER_LOGOUT_CLICK,
  UI__TOGGLE_EXPANDABLE_CARDGROUP,
  UI__TOGGLE_RUNNER_INFO,
  SAW_CARD,
  UI__FILTERS_RESET_CLICK,
  UI__FILTER_APPLY,
  UI__FILTER_CLOSE,
  UI__FILTER_OPEN,
  UI__TOGGLE_SHOW_MORE_RUNNERS,
  UI__STATISTICS_MODAL_TOGGLE,
  UI__STATISTICS_ITEM_CLICK,
  UI__NEXT_RACES_RACE_FILTER_CLICK,
  UI__AZ_SWITCH_CLICK,
  UI__PROMO_DESCRIPTION_TOGGLE,
  UI__RACE_REPLAYS_TOGGLE,
  UI__CLICK_PROMOTION_CALL_TO_ACTION,
  UI__CLICK_PROMOTION_TERMS_AND_CONDITIONS,
  UI__CONTENT_SUMMARY_COLLAPSE_EVENT,
  UI__NEXT_RACES_RACE_CLICK,
  UI__SWITCHER_OPEN,
  UI__NAVIGATION_TAB_CLICK,
  UI__TOGGLE_TIMEFORM_CARD,
  UI__GENEROSITY_WALLET_BUTTON_CLICK,
  UI__GENEROSITY_WALLET_CLOSE_CLICK,
  UI__FREE_BETS_WALLET_TOGGLE_CLICK,
  HAMBURGER_MENU_OPEN,
  HAMBURGER_MENU_CLOSE,
  UI__GENEROSITY_WALLET_PEBBLE_CLICK,
  UI__GENEROSITY_WALLET_APPLY_BUTTON_CLICK,
  UI__BETSLIP_SLIDER_INTERACTION,
  UI__BETSLIP_SLIDER_DISPLAYED,
} from "../actions/interface";
import {
  NETWORK__CANCEL_EXC_BET_FAILURE,
  NETWORK__CANCEL_EXC_BET_SUCCESS,
  NETWORK__PLACE_EXC_BET_FAILURE,
  NETWORK__UPDATE_EXC_BET_FAILURE,
  UI__BETSLIP_ACCORDION_HEADER_CLICK,
  UI__BETSLIP_SBK_TAB_SWITCH,
  UI__BETSLIP_BET_BUILDER_REMOVE_SELECTIONS,
  UI__BETSLIP_EXC_CONFIRM_BET_CLICK,
  UI__BETSLIP_EXC_LOGIN_TO_PLACE_BET_CLICK,
  UI__BETSLIP_EXC_PLACE_BET_CLICK,
  UI__BETSLIP_EXC_PLACE_BET_CLICK_AUTO_CONFIRM,
  UI__BETSLIP_EXC_PRICE_NUDGE_DOWN,
  UI__BETSLIP_EXC_PRICE_NUDGE_UP,
  UI__BETSLIP_EXC_REPORT_EDIT_BET_CLICK,
  UI__BETSLIP_EXC_UNMATCHED_CANCEL_CLICK,
  UI__BETSLIP_EXC_UNMATCHED_DONE_CLICK,
  UI__BETSLIP_EXC_UNMATCHED_PERSISTENCE_ITEM_CLICK,
  UI__BETSLIP_EXC_UNMATCHED_PERSISTENCE_LIST_CLICK,
  UI__BETSLIP_EXC_UNMATCHED_PRICE_NUDGE_DOWN,
  UI__BETSLIP_EXC_UNMATCHED_PRICE_NUDGE_UP,
  UI__BETSLIP_EXC_UNMATCHED_UPDATE_CLICK,
  UI__BETSLIP_HEADER_CLICK,
  UI__BETSLIP_SBK_LOGIN_TO_PLACE_BET_CLICK,
  UI__BETSLIP_SBK_DEPOSIT_TO_PLACE_BET_CLICK,
  UI__BETSLIP_SBK_DEPOSIT_TO_CONFIRM_BET_CLICK,
  UI__BETSLIP_SBK_MULTIPLE_BET_TYPE_CLICK,
  UI__BETSLIP_SBK_PLACE_BETS_CLICK,
  UI__BETSLIP_SBK_PLACE_BETS_CLICK_AUTO_CONFIRM,
  UI__BETSLIP_SBK_CONFIRM_BETS_CLICK,
  UI__BETSLIP_SBK_EDIT_BETS_CLICK,
  UI__BETSLIP_SBK_INCREMENT_STAKE_ACTION,
  UI__BETSLIP_EXC_INCREMENT_SIZE_ACTION,
  UI__BETSLIP_SBK_REMOVE_LEG_CLICK,
  UI__BETSLIP_SBK_REMOVE_SELECTIONS,
  UI__BETSLIP_SBK_RE_ADD_SELECTIONS_CLICK,
  UI__BETSLIP_SBK_NOTIFICATION_SHOWN,
  UI__BETSLIP_OBB_NOTIFICATION_SHOWN,
  UI__BETSLIP_SBK_MAX_PAYOUT_NOTIFICATION_URL_CLICK,
  UI__BETSLIP_EXC_RECEIPT_PANEL_DONE_CLICK,
  UI__BETSLIP_SBK_RECEIPT_BET_ID_COPY,
  UI__BETSLIP_SBK_RECEIPT_REGULATOR_BET_ID_COPY,
  UI__BETSLIP_MAX_PAYOUT_NOTIFICATION_ACCEPTED,
  UI__BETSLIP_SBK_EACH_WAY_TOGGLE,
  UI__BETSLIP_SBK_ACCA_INSURANCE_TOGGLE,
  UI__BETSLIP_SBK_CAST_BET_CHANGE,
  UI__BETSLIP_SBK_CAST_BET_ORDER_CHANGE,
  UI__BETSLIP_SBK_PRICE_BOOST_TOGGLE,
  UI__BETSLIP_EXC_BONUS_CHANGE,
  UI__BETSLIP_BET_BUILDER_ADD_SELECTIONS,
  NETWORK__PLACE_EXC_BET_SUCCESS,
  NETWORK__UPDATE_EXC_BET_SUCCESS,
  UI__BETSLIP_OPEN,
  UI__BETSLIP_EXC_REMOVE_POTENTIAL_SELECTION,
  UI__BETSLIP_SBK_REMOVE_POTENTIAL_SELECTION,
  UI__BETSLIP_EXC_REMOVE_POTENTIAL_BET_CLICK,
  NETWORK__PLACE_SBK_BET_SUCCESS,
  NETWORK__OBB_PLACE_BET_SUCCESS,
} from "../actions/betslip";
import {
  UI__USER_PROFILE_BUDGET_LINK_CLICK,
  UI__USER_PROFILE_EYE_ICON_CLICK,
  UI__USER_PROFILE_MENU_LINK_CLICK,
  UI__USER_PROFILE_QUICK_LINK_CLICK,
  UI__USER_PROFILE_TOGGLE_CASH_BALANCES_VIEW_CLICK,
} from "../actions/user-profile";
import { UPDATE_MARKET_DEPTH, UI__SWITCH_PRODUCT_PREFERENCE } from "../actions/preferences";
import { UI__OPEN_PREDICTS } from "../actions/predicts";
import {
  BETTING__OBB_SBK_CLEAR_ACTION,
  BETTING__OBB_SBK_KEEP_ACTION,
  BETTING__OBB_TOGGLE_LEG_ACTION,
  BETTING__SBK_ADD_SELECTION_TAGGING,
  BETTING__SBK_BONUS_TOGGLE_ACTION,
  BETTING__SBK_PLACE_FAILED_UPDATE,
  BETTING__SPORTSBOOK_REMOVE_ALL_FREE_BETS_WALLETS_ACTION,
  BETTING__SPORTSBOOK_GENEROSITY_WALLET_BET_ACTION,
  UI__MARKET_EXC_BET_BUTTON_CLICK,
  BETTING__OBB_PLACE_FAILED_UPDATE,
  BETTING__OBB_TOGGLE_MULTIPLE_LEG_ACTION,
  UI__GENEROSITY_WALLET_REMOVE_CLICK,
} from "../actions/betting";
import {
  UI__SEARCH_AZ_LINK_CLICK,
  UI__SEARCH_LINK_CLICK,
  UI__SEARCH_BAR_LINK_CLICK,
  UI__SEARCH_TAB_CLICK,
  UI__SEARCH_BAR_FOCUS,
  UI__SEARCH_CANCEL_CLICK,
  UI__CLEAR_SEARCH_RESULTS,
  UI__SEARCH_HISTORY_CLICK,
} from "../actions/browse";
import {
  getBetslipBetBuilderRemoveSelections,
  getBetslipExchangeLoginToPlaceBetClickEvent,
  getBetslipSportsbookLoginToPlaceBetClickEvent,
  getDontUpdateBetClickEvent,
  getExchangeOnClickEdit,
  getMyBetsCancelAllUnmatchedExchangeBetsFailure,
  getMyBetsCancelAllUnmatchedExchangeBetsSuccess,
  getMyBetsCancelUnmatchedExchangeBetFailure,
  getMyBetsCancelUnmatchedExchangeBetSuccess,
  getUpdateBetClickEvent,
  getBetslipSportsbookRemoveSelectionEvent,
  getBetslipExchangeRemovePotentialSelectionEvent,
  getBetslipSportsbookRemovePotentialSelectionEvent,
  getBetslipCancelBetSuccessClickEvent,
  getBetslipCancelBetFailureClickEvent,
  getBetslipCancelUnmatchedBetClickEvent,
  getBetslipExchangeRemovePotentialBetClickEvent,
} from "./ga4-tagging-resolvers/betslip";
import { ACCEPT_PROMOTION, INTERACT_CANCEL_PROMOTION_MODAL, REFRESH_PROMOTION } from "../actions/promotion";
import { getAcceptPromotionEvent, getCancelPromotionEvent } from "./ga4-tagging-resolvers/promotions";
import { BOTTOM_BAR_PUSH, EXTERNAL_PUSH } from "../actions";
import { UI__CLOSED_SBK_CLICK, UI__SUSPENDED_SBK_CLICK } from "../actions/sportsbook-markets";
import { getPromotionClickEvent } from "./ga4-tagging-resolvers/banner";
import {
  UI__BROADCASTS_AND_STATISTICS_CARD_TOGGLE,
  UI__BROADCASTS_AND_STATISTICS_MEDIA_PLAYER_LOADED,
  UI__BROADCASTS_CARD_TOGGLE,
  UI__MEDIA_PLAYER_LOADED,
  UI__TIME_FORM_BROADCASTS_CARD_MEDIA_PLAYER_EVENT,
  UI__TIME_FORM_BROADCASTS_CARD_TOGGLE,
  UI__RACE_REPLAYS_MEDIA_PLAYER_LOADED,
} from "../actions/media";
import {
  getBroadcastsAndStatisticsCardMediaPlayerEvent,
  getMediaPlayerLoadedEvent,
  getTimeFormBroadCastsMediaPlayerEvent,
  getRaceReplaysMediaPlayerEvent,
} from "./ga4-tagging-resolvers/video-saw";
import {
  getAutoConfirmCashoutClickEvent,
  getCashoutClickEvent,
  getCashoutFailureEvent,
  getCashoutFailureSbkEvent,
  getCashoutSuccessEvent,
} from "./ga4-tagging-resolvers/my-bets";
import {
  getSmartAppBannerClickEvent,
  getSmartAppBannerCloseEvent,
  getSmartAppBannerDisplayEvent,
} from "./ga4-tagging-resolvers/notification";
import {
  NETWORK__CASHOUT_TAKE_FAILURE,
  NETWORK__CASHOUT_TAKE_FAILURE_SBK,
  NETWORK__CASHOUT_TAKE_SUCCESS,
  UI__CASHOUT_BUTTON_TAP,
  UI__CASHOUT_BUTTON_TAP_AUTO_CONFIRM,
} from "../actions/cashout";
import {
  getBetslipBetBuilderAddSelections,
  getExchangeAddSelectionToBetslip,
  getObbToggleLegEvent,
  getSportsbookAddSelectionToBetslip,
  getObbToggleMultipleLegEvent,
} from "./ga4-tagging-resolvers/added-selection";
import {
  getExchangeBetEditSuccessfullEvents,
  getExchangeSuccessPlaceBetEvents,
  getObbPlaceBetSuccessEvent,
  getSportsbookSuccessPlaceBetsEvents,
} from "./ga4-tagging-resolvers/placed-bet";
import { DEPOSIT_FLOW, DEPOSIT_SUCCESS, FIRST_DEPOSIT_SUCCESS } from "../actions/deposit";
import { getFirstDepositSuccessEvent } from "./ga4-tagging-resolvers/first-deposit-success";
import { getDepositSuccessEvent } from "./ga4-tagging-resolvers/deposit-success";
import { getDepositFlowEvent } from "./ga4-tagging-resolvers/deposit-flow";
import { UI__JACKPOT_MERCHANDISE_VIEW, UI__PAGE_CONTENT_LOADED } from "../actions/game-interactions";
import { ADD_USER_FAVOURITE_GAME, REMOVE_USER_FAVOURITE_GAME } from "../actions/user-favourite-games";
import {
  UI__SEARCH_BAR_INPUT_FOCUS,
  UI__SEARCH_BAR_CANCEL_CLICK,
  UI__SEARCH_BAR_INPUT_CHANGE_CLEAR,
  UI__SPORTS_FILTER_CLICK,
} from "../actions/search-bar-state";
import {
  OBB_CARD__EVENT_SELECTION,
  UI__CLOSE_PLAYER_PICKER_MODAL,
  UI__SQUAD_BET_PLAYER_PICKER_OPEN,
  UI__TOGGLE_SQUAD_BET_PLAYER_PICKER_SQUAD_PARTICIPANT,
  UI__SQUAD_BET_PLAYER_PICKER_BET_BUTTON_CLICK,
  UI__OBB_ENHANCED_TRACKING_PLAYER_COUNTER,
  UI__SQUAD_VS_SQUAD_TOGGLE_PLAYERS_TOOLTIP,
  OBB_CARD_GROUP__SECTION_TOGGLED,
  OBB_CARD_GROUP__LAYOUT_SELECTION,
  OBB_CARD_GROUP__SHOW_MORE_CLICKED,
  UI__SQUAD_BET_PLAYER_PICKER_REMOVE_SQUAD_PARTICIPANT,
  OBB_EVENT_POPULARS_CARD__SHOW_MORE_CLICKED,
  OBB_ONBOARDING_CARDS__CARD_GROUP_SWIPED,
  OBB_ONBOARDING_CARDS__CARD_GROUP_DISPLAYED,
} from "../actions/obb";
import { UI__ACTION_CONFIRMATION } from "../actions/confirmation";
import {
  NETWORK__FETCH_GAMING_SEARCH_RESULTS_SUCCESS,
  UI__GAMING__CLEAR_SEARCH_RESULTS,
  UI__GAMING__SEARCH_BAR_INPUT_FOCUS,
  UI__GAMING__SEARCH_CANCEL_CLICK,
  UI__GAMING__SEARCH_HISTORY_PEBBLE_CLICK,
} from "../actions/gaming-search";
import {
  UI__SMART_APP_BANNER_CLICK,
  UI__SMART_APP_BANNER_CLOSE,
  UI__SMART_APP_BANNER_DISPLAY,
} from "../actions/notification";
import {
  UI__FAVOURITE_MARKETS_LIMIT_REACHED_MESSAGE_CLOSE,
  UI__FAVOURITE_MARKETS_TOGGLE_FAVOURITE,
  UI__FAVOURITE_MARKETS_TOOLTIP_CLOSE,
} from "../actions/favourite-markets";

const ACTION_TAGGING_MAPPER: ActionTaggingMapper = {
  [URL__BETSLIP_DEEPLINK]: getBetslipDeeplinkEvent as TaggingBuilder,
  [UI__MY_BETS_EXC_ORDER_STATUS_SWITCH]: getMyBetsExchangeOrderStatusClickEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_COMPETITION_VIEW]: getCompetitionLinkClickEvent as TaggingBuilder,
  [PN_SUBSCRIBE_EVENTS]: getBetReceiptToggleClickEvent as TaggingBuilder,
  [PN_UNSUBSCRIBE_EVENTS]: getBetReceiptToggleClickEvent as TaggingBuilder,
  [PN_SUBSCRIBE_EVENTS_SUCCESS]: getBetReceiptSuccessMessageSawEvent as TaggingBuilder,
  [PN_PARTIAL_SUBSCRIBE_EVENTS_SUCCESS]: getBetReceiptSuccessMessageSawEvent as TaggingBuilder,
  [PN_UNSUPPORTED_SUBSCRIBE_EVENTS_SUCCESS]: getBetReceiptSuccessMessageSawEvent as TaggingBuilder,
  [UI__PLAY_NEW_LOADED]: getLoadPlayNewEvent as TaggingBuilder,
  [UI__PLAY_NEW_MORE_INFO_BUTTON_CLICK]: getMoreInfoPlayNewClickEvent as TaggingBuilder,
  [UI__LAUNCH_GAME]: getGameTileClickEvent as TaggingBuilder,
  [UI__LAUNCH_GAME_FROM_GAME_INFO]: getGameLaunchFromGameInfoEvent as TaggingBuilder,
  [UI__LAUNCH_GAME_FROM_PN]: getGameLaunchFromPNEvent as TaggingBuilder,
  [UI__LAUNCH_GAME_FROM_PROMO]: getGameLaunchFromPromoEvent as TaggingBuilder,
  [UI__LAUNCH_GAME_FROM_WIDGET]: getGameLaunchFromWidgetEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_GAMING_CATEGORY_USING_CATEGORY_LINK_CARD]: getNavigateToGameCategoryEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_GAME_INFO_VIEW]: getNavigateToGameInfoEvent as TaggingBuilder,
  [UI__PLAY_NEW_PLAY_NOW_BUTTON_CLICK]: getPlayNowPlayNewClickEvent as TaggingBuilder,
  [UI__FOOTER_LINK_CLICK]: getLinkClickEvent as TaggingBuilder,
  [UI__MY_ACCOUNT_ICON_CLICK]: getMyAccountMenuToggleEvent as TaggingBuilder,
  [UI__USER_LOGOUT_CLICK]: getLogoutClickEvent as TaggingBuilder,
  [UI__BETSLIP_HEADER_CLICK]: getBetslipHeaderClickEvent as TaggingBuilder,
  [UI__BETSLIP_ACCORDION_HEADER_CLICK]: getBetslipAccordionHeaderClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_TAB_SWITCH]: getBetslipSportsbookTabSwitchEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_CONFIRM_BETS_CLICK]: getConfirmSportsbookBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_EDIT_BETS_CLICK]: getEditSportsbookBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_DONE_CLICK]: getDontUpdateBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_UPDATE_CLICK]: getUpdateBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_CANCEL_CLICK]: getBetslipCancelUnmatchedBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_PRICE_NUDGE_UP]: getExchangePriceChangeEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_PRICE_NUDGE_DOWN]: getExchangePriceChangeEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_PRICE_NUDGE_UP]: getExchangePriceChangeEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_PRICE_NUDGE_DOWN]: getExchangePriceChangeEvent as TaggingBuilder,
  [NETWORK__CANCEL_EXC_BET_SUCCESS]: getBetslipCancelBetSuccessClickEvent as TaggingBuilder,
  [NETWORK__CANCEL_EXC_BET_FAILURE]: getBetslipCancelBetFailureClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_REPORT_EDIT_BET_CLICK]: getExchangeOnClickEdit as TaggingBuilder,
  [NETWORK__UPDATE_EXC_BET_FAILURE]: getUpdateBetFailureEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_PERSISTENCE_ITEM_CLICK]: getChangePersistenceTypeClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_UNMATCHED_PERSISTENCE_LIST_CLICK]: getOpenPersistenceTypeMenuEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_PLACE_BET_CLICK]: getPlaceExchangeBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_PLACE_BET_CLICK_AUTO_CONFIRM]: getExchangeAutoConfirmedBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_CONFIRM_BET_CLICK]: getExchangeConfirmBetClickEvent as TaggingBuilder,
  [NETWORK__PLACE_EXC_BET_FAILURE]: getExchangeFailedPlaceBetEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_MULTIPLE_BET_TYPE_CLICK]: getBetslipSportsbookMultipleBetTypeClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_PLACE_BETS_CLICK]: getPlaceSportsbookBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_PLACE_BETS_CLICK_AUTO_CONFIRM]: getAutoConfirmSportsbookBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_INCREMENT_STAKE_ACTION]: getSbkIncrementStakeEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_INCREMENT_SIZE_ACTION]: getExcIncrementSizeEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_REMOVE_LEG_CLICK]: getBetslipSportsbookRemoveSelectionEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_REMOVE_SELECTIONS]: getBetslipSbkRemoveAllEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_RE_ADD_SELECTIONS_CLICK]: getBetslipSbkReAddSelectionsEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_NOTIFICATION_SHOWN]: getBetslipSbkNotificationShownEvent as TaggingBuilder,
  [UI__BETSLIP_OBB_NOTIFICATION_SHOWN]: getBetslipObbNotificationShownEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_MAX_PAYOUT_NOTIFICATION_URL_CLICK]:
    getBetslipSbkMaxPayoutNotificationUrlClickEvent as TaggingBuilder,
  [UI__MARKET_RULES_MODAL_TOGGLE]: getMarketRulesToggleModalEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_DISCOUNT_RATE_EXPLAINED]: getMarketRulesLinkClickEvent as TaggingBuilder,
  [UI__CLICK_ALLMARKETS_LINK]: getAllMarketsLinkClickEvent as TaggingBuilder,
  [UI__TAP_ALL_COMPETITIONS_LINK]: getAllCompetitionsLinkClickEvent as TaggingBuilder,
  [UI__GRAPH_TOGGLE]: getToggleMarketGraphEvent as TaggingBuilder,
  [UI__RECENT_RACE_TOGGLE]: getToggleRecentRacesEvent as TaggingBuilder,
  [UI__CLICK_MARKET_GRAPH_TAB_VIEW_SELECTOR]: getMarketGraphSelectViewEvent as TaggingBuilder,
  [UI__CLICK_MARKET_GRAPH_MODE_SELECTOR]: getMarketGraphSelectGraphEvent as TaggingBuilder,
  [UI__USER_PROFILE_MENU_LINK_CLICK]: getMyAccountMenuLinkEvent as TaggingBuilder,
  [UI__USER_PROFILE_QUICK_LINK_CLICK]: getMyAccountQuickLinkEvent as TaggingBuilder,
  [UI__USER_PROFILE_EYE_ICON_CLICK]: getMyAccountEyeIconEvent as TaggingBuilder,
  [UI__USER_PROFILE_TOGGLE_CASH_BALANCES_VIEW_CLICK]: getMyAccountToggleCashBalancesViewEvent as TaggingBuilder,
  [UI__USER_PROFILE_BUDGET_LINK_CLICK]: getLinkClickEvent as TaggingBuilder,
  [UPDATE_MARKET_DEPTH]: getMarketDepthClickEvent as TaggingBuilder,
  [UI__BOTTOM_BAR_CLICK]: getBottomBarClickEvent as TaggingBuilder,
  [UI__BOTTOM_BAR_GAME_LAUNCH]: getGameLaunchFromBottomBar as TaggingBuilder,
  [UI__NAVIGATE_TO_GAMING_CATEGORY_USING_SEE_ALL_BUTTON]: getSeeAllLinkClickEvent as TaggingBuilder,
  [UI__CLICK_PEBBLE_ITEM]: getPebbleSelectionClickEvent as TaggingBuilder,
  [BETTING__SBK_PLACE_FAILED_UPDATE]: getSportsbookFailedPlaceBetEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_RECEIPT_PANEL_DONE_CLICK]: getBetReceiptExchangeDoneClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_RECEIPT_BET_ID_COPY]: getBetReceiptCopyToClipboardEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_RECEIPT_REGULATOR_BET_ID_COPY]: getBetReceiptCopyToClipboardEvent as TaggingBuilder,
  [UI__SEARCH_TAB_CLICK]: getSearchTabClickEvent as TaggingBuilder,
  [UI__SEARCH_AZ_LINK_CLICK]: getSearchAzLinkClickEvent as TaggingBuilder,
  [UI__SEARCH_LINK_CLICK]: getSearchLinkClickEvent as TaggingBuilder,
  [UI__SEARCH_BAR_LINK_CLICK]: getSearchLinkClickEvent as TaggingBuilder,
  [UI__SEARCH_BAR_FOCUS]: getSearchBarFocusEvent as TaggingBuilder,
  [UI__SEARCH_BAR_INPUT_FOCUS]: getSearchBarFocusEvent as TaggingBuilder,
  [UI__SEARCH_BAR_INPUT_CHANGE_CLEAR]: getSearchClearClickEvent as TaggingBuilder,
  [UI__SEARCH_CANCEL_CLICK]: getSearchCancelClickEvent as TaggingBuilder,
  [UI__SEARCH_BAR_CANCEL_CLICK]: getSearchCancelClickEvent as TaggingBuilder,
  [UI__SPORTS_FILTER_CLICK]: getSportsFilterClickEvent as TaggingBuilder,
  [UI__SEARCH_HISTORY_CLICK]: getSearchHistoryClickEvent as TaggingBuilder,
  [UI__CLEAR_SEARCH_RESULTS]: getSearchClearClickEvent as TaggingBuilder,
  [UI__GAMING__SEARCH_CANCEL_CLICK]: getGamingSearchCancelClickEvent as TaggingBuilder,
  [UI__GAMING__SEARCH_HISTORY_PEBBLE_CLICK]: getGamingSearchHistoryPebbleClickEvent as TaggingBuilder,
  [UI__GAMING__SEARCH_BAR_INPUT_FOCUS]: getGamingSearchBarFocusEvent as TaggingBuilder,
  [UI__GAMING__CLEAR_SEARCH_RESULTS]: getGamingSearchClearClickEvent as TaggingBuilder,
  [NETWORK__FETCH_GAMING_SEARCH_RESULTS_SUCCESS]: getGamingSearchResults as TaggingBuilder,
  [UI__LOGO_CLICK]: getLogoClickEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_MARKET_VIEW]: getNavigateToMarketViewEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_SWITCHER_OPTION_CLICK]: getNavigateToSwitcherOptionClickEvent as TaggingBuilder,
  [UI__TOGGLE_RUNNER_INFO]: getToggleRunnerInfoEvent as TaggingBuilder,
  [UI__TOGGLE_EXPANDABLE_CARDGROUP]: getToggleExpandableCardGroupEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_VIEW]: getNavigateToView as TaggingBuilder,
  [UI__FILTER_OPEN]: getFilterOpenEvent as TaggingBuilder,
  [UI__FILTER_CLOSE]: getFilterCloseEvent as TaggingBuilder,
  [UI__FILTER_APPLY]: getFilterApplyEvent as TaggingBuilder,
  [UI__FILTERS_RESET_CLICK]: getFilterResetClickEvent as TaggingBuilder,
  [ACCEPT_PROMOTION]: getAcceptPromotionEvent as TaggingBuilder,
  [REFRESH_PROMOTION]: getCancelPromotionEvent as TaggingBuilder,
  [INTERACT_CANCEL_PROMOTION_MODAL]: getCancelPromotionEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_SEE_ALL_PROMOTIONS]: getNavigationSeeAllPromotionsEvent as TaggingBuilder,
  [EXTERNAL_PUSH]: getNavigateToEvent as TaggingBuilder,
  [BOTTOM_BAR_PUSH]: getBottomBarPushEvent as TaggingBuilder,
  [SAW_CARD]: getSawCardEvent as TaggingBuilder,
  [UI__NOT_FOUND_VIEW_LOADED]: getLoadedNotFoundView as TaggingBuilder,
  [UI__NAVIGATE_FROM_NOT_FOUND_VIEW]: getNavigateFromNotFoundView as TaggingBuilder,
  [UI__SWITCH_PRODUCT_PREFERENCE]: getSwitchProductEvent as TaggingBuilder,
  [UI__OPEN_PREDICTS]: getOpenPredictsEvent as TaggingBuilder,
  [UI__MY_BETS_BET_SHARING_DISMISS_TAP]: getMyBetsBetSharingDismissEvent as TaggingBuilder,
  [UI__MY_BETS_HEADER_TOOLTIP_TOGGLE]: getMyBetsHeaderTooltipToggleEvent as TaggingBuilder,
  [UI__MY_BETS_BET_SHARING_PREVIEW_TAP]: getMyBetsBetSharingPreviewEvent as TaggingBuilder,
  [UI__MY_BETS_BET_SHARING_SHARE_BET_TAP]: getMyBetsBetSharingShareBetEvent as TaggingBuilder,
  [UI__MY_BETS_BET_SHARING_SHARE_IMAGE_TAP]: getMyBetsBetSharingShareImageEvent as TaggingBuilder,
  [UI__MY_BETS_ACCA_FREEZE_OPENED]: getMyBetsAccaFreezeOpenedEvent as TaggingBuilder,
  [UI__MY_BETS_ACCA_FREEZE_CLOSED]: getMyBetsAccaFreezeClosedEvent as TaggingBuilder,
  [UI__BET_MUTATION_ACCA_FREEZE_SELECTED]: getBetMutationAccaFreezeSelectedEvent as TaggingBuilder,
  [UI__BET_MUTATION_ACCA_FREEZE_DESELECTED]: getBetMutationAccaFreezeDeselectedEvent as TaggingBuilder,
  [NETWORK__FREEZE_BET]: getBetMutationAccaFreezeConfirmEvent as TaggingBuilder,
  [NETWORK__MY_BETS_CANCEL_UNMATCHED_EXC_BET_SUCCESS]: getMyBetsCancelUnmatchedExchangeBetSuccess as TaggingBuilder,
  [NETWORK__MY_BETS_CANCEL_UNMATCHED_EXC_BETS_FAILURE]: getMyBetsCancelUnmatchedExchangeBetFailure as TaggingBuilder,
  [UI__MY_BETS_CANCEL_ALL_UNMATCHED_PRESS]: getMyBetsCancelAllEvent as TaggingBuilder,
  [NETWORK__MY_BETS_CANCEL_ALL_UNMATCHED_EXC_BETS_SUCCESS]:
    getMyBetsCancelAllUnmatchedExchangeBetsSuccess as TaggingBuilder,
  [NETWORK__MY_BETS_CANCEL_ALL_UNMATCHED_EXC_BETS_FAILURE]:
    getMyBetsCancelAllUnmatchedExchangeBetsFailure as TaggingBuilder,
  [UI__MY_BETS_EXC_EDIT_BET_PRESS]: getExchangeMyBetsEditClickEvent as TaggingBuilder,
  [UI__MY_BETS_EXC_EDIT_BET_CLOSE]: getMyBetsEditBottomSheetCloseEvent as TaggingBuilder,
  [PN_INTERACTION_EVENT]: getPNInteractionClickEvent as TaggingBuilder,
  [PN_MYBETS_SINGLES_BELL_CLICK]: getMyBetsSinglesBellClickEvent as TaggingBuilder,
  [PN_MYBETS_MULTIPLES_BELL_CLICK]: getMyBetsMultiplesBellClickEvent as TaggingBuilder,
  [PN_MYBETS_NOTIFICATIONS_CLOSE]: getMyBetsNotificationsCloseEvent as TaggingBuilder,
  [PN_MYBETS_SAVE_CLICK]: getMyBetsSaveClickEvent as TaggingBuilder,
  [PN_EVENT_PAGE_NOTIFICATIONS_TOGGLE]: getEventPageNotificationsToggleEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_EVENT_FROM_COUPON_PRIMARY_MARKET]: getCouponViewCardClickEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_EVENT_FROM_SPORT]: getNavigateToEventFromSportEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_EVENT_FROM_MARKET_SCOREBOARD]: getNavigateToEventFromPlayerPage as TaggingBuilder,
  [UI__TOGGLE_SHOW_MORE_RUNNERS]: getToggleShowMoreEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_FAQ_PAGE]: getMarketBlurbFAQEvent as TaggingBuilder,
  [UI__BETSLIP_BET_BUILDER_REMOVE_SELECTIONS]: getBetslipBetBuilderRemoveSelections as TaggingBuilder,
  [UI__BETSLIP_SBK_LOGIN_TO_PLACE_BET_CLICK]: getBetslipSportsbookLoginToPlaceBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_DEPOSIT_TO_PLACE_BET_CLICK]: getBetslipSbkDepositToPlaceBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_DEPOSIT_TO_CONFIRM_BET_CLICK]: getBetslipSbkDepositToConfirmBetClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_LOGIN_TO_PLACE_BET_CLICK]: getBetslipExchangeLoginToPlaceBetClickEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_EVENT_FROM_BETSLIP_PP_BET_BUILDER]: getBetslipBetBuilderNavigateToEvent as TaggingBuilder,
  [UI__NAVIGATE_TO_BET_BUILDER_EVENT_FROM_PP_BET_BUILDER]: getPopularBetBuildNavigateToEventBetBuild as TaggingBuilder,
  [UI__QUICK_LINK_CLICK]: getQuickLinkClickEvent as TaggingBuilder,
  [UI__STATISTICS_MODAL_TOGGLE]: getStatisticsModalToggleEvent as TaggingBuilder,
  [UI__STATISTICS_ITEM_CLICK]: getStatisticsItemClickEvent as TaggingBuilder,
  [UI__NEXT_RACES_RACE_FILTER_CLICK]: getNextRacesRaceFilterClickEvent as TaggingBuilder,
  [UI__CLOSED_SBK_CLICK]: getMarketSnackBarClosedEvent as TaggingBuilder,
  [UI__SUSPENDED_SBK_CLICK]: getMarketSnackBarSuspendedEvent as TaggingBuilder,
  [UI__AZ_SWITCH_CLICK]: getAzSwitchToggleEvent as TaggingBuilder,
  [UI__MY_BETS_ORDER_TYPE_FILTER_CLICK]: getMyBetsOrderTypeFilterClickEvent as TaggingBuilder,
  [UI__PROMO_DESCRIPTION_TOGGLE]: getPromoDescriptionToggleEvent as TaggingBuilder,
  [UI__MY_BETS_ON_ACCORDION_TOGGLE]: getToggleAccordionEvent as TaggingBuilder,
  [UI__MY_BETS_HERITAGE_TOGGLE_FILTER_CLICK]: getHeritageToggleClickEvent as TaggingBuilder,
  [UI__MY_BETS_HERITAGE_INFO_LABEL_CLICK]: getHeritageInfoLabelClickEvent as TaggingBuilder,
  [UI__MY_BETS_COPY_BET_ID]: getMyBetsCopyBetIdToClipboardEvent as TaggingBuilder,
  [UI__MY_BETS_COPY_REGULATOR_BET_ID]: getMyBetsCopyBetIdToClipboardEvent as TaggingBuilder,
  [UI__MY_BETS_COPY_DEVICE_ID]: getMyBetsCopyDeviceIdToClipboardEvent as TaggingBuilder,
  [UI__RACE_REPLAYS_MEDIA_PLAYER_LOADED]: getRaceReplaysMediaPlayerEvent as TaggingBuilder,
  [UI__RACE_REPLAYS_TOGGLE]: getRaceReplaysToggleEvent as TaggingBuilder,
  [UI__BETSLIP_MAX_PAYOUT_NOTIFICATION_ACCEPTED]: getMaxPayoutAcceptMessageClickEvent as TaggingBuilder,
  [UI__CLICK_PROMOTION_CALL_TO_ACTION]: getPromotionClickEvent as TaggingBuilder,
  [UI__CLICK_PROMOTION_TERMS_AND_CONDITIONS]: getPromotionClickEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_BONUS_CHANGE]: getBetslipBonusActivationEvent as TaggingBuilder,
  [BETTING__SBK_BONUS_TOGGLE_ACTION]: getBetslipBonusActivationEvent as TaggingBuilder,
  [UI__NAVIGATE_FROM_CONTENT_SUMMARY_VIEW_LINK]: getLinkClickEvent as TaggingBuilder,
  [UI__CONTENT_SUMMARY_COLLAPSE_EVENT]: getContentSummaryCollapseEvent as TaggingBuilder,
  [UI__RACE_VIEW_LINKS_LINK_CLICK]: getRaceViewLinksLinkClickEvent as TaggingBuilder,
  [UI__NEXT_RACES_RACE_CLICK]: getNextRacesRaceClickEvent as TaggingBuilder,
  [UI__JACKPOT_MERCHANDISE_VIEW]: getJackpotMerchandiseViewEvent as TaggingBuilder,
  [UI__PAGE_CONTENT_LOADED]: getLoadedPageContentEvent as TaggingBuilder,
  [ADD_USER_FAVOURITE_GAME]: getAddGameToFavouritesEvent as TaggingBuilder,
  [REMOVE_USER_FAVOURITE_GAME]: getRemoveGameFromFavouritesEvent as TaggingBuilder,
  [UI__BROADCASTS_CARD_TOGGLE]: getBroadcastsToggleEvent as TaggingBuilder,
  [UI__MEDIA_PLAYER_LOADED]: getMediaPlayerLoadedEvent as TaggingBuilder,
  [UI__BROADCASTS_AND_STATISTICS_CARD_TOGGLE]: getBroadcastsAndStatisticsToggleEvent as TaggingBuilder,
  [UI__BROADCASTS_AND_STATISTICS_MEDIA_PLAYER_LOADED]: getBroadcastsAndStatisticsCardMediaPlayerEvent as TaggingBuilder,
  [UI__TIME_FORM_BROADCASTS_CARD_TOGGLE]: getTimeFormBroadCastsToggleEvent as TaggingBuilder,
  [UI__TIME_FORM_BROADCASTS_CARD_MEDIA_PLAYER_EVENT]: getTimeFormBroadCastsMediaPlayerEvent as TaggingBuilder,
  [UI__BACK_BUTTON_CLICK]: getLinkClickEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_EACH_WAY_TOGGLE]: getBetslipEachWayToggleEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_ACCA_INSURANCE_TOGGLE]: getBetslipAccaInsuranceToggleEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_PRICE_BOOST_TOGGLE]: getBetslipMyOddsBoostToggleEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_CAST_BET_CHANGE]: getBetslipCastBetChangeEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_CAST_BET_ORDER_CHANGE]: getBetslipCastBetOrderChangeEvent as TaggingBuilder,
  [UI__SWITCHER_OPEN]: getSwitcherEvent as TaggingBuilder,
  [UI__CASHOUT_BUTTON_TAP]: getCashoutClickEvent as TaggingBuilder,
  [UI__CASHOUT_BUTTON_TAP_AUTO_CONFIRM]: getAutoConfirmCashoutClickEvent as TaggingBuilder,
  [NETWORK__CASHOUT_TAKE_SUCCESS]: getCashoutSuccessEvent as TaggingBuilder,
  [NETWORK__CASHOUT_TAKE_FAILURE]: getCashoutFailureEvent as TaggingBuilder,
  [NETWORK__CASHOUT_TAKE_FAILURE_SBK]: getCashoutFailureSbkEvent as TaggingBuilder,
  [UI__NAVIGATION_TAB_CLICK]: getNavigationTabClickEvent as TaggingBuilder,
  [UI__CARDGROUP_VIEW_ALL_LINK_TAP]: getViewAllTapEvent as TaggingBuilder,
  [UI_NAVIGATE_VIEW_FROM_FAVOURITES]: getViewFromFavouritesClickEvent as TaggingBuilder,
  [UI__BETSLIP_BET_BUILDER_ADD_SELECTIONS]: getBetslipBetBuilderAddSelections as TaggingBuilder,
  [UI__TOGGLE_TIMEFORM_CARD]: getToggleTimeFormEvent as TaggingBuilder,
  [NETWORK__PLACE_EXC_BET_SUCCESS]: getExchangeSuccessPlaceBetEvents as TaggingBuilder,
  [NETWORK__UPDATE_EXC_BET_SUCCESS]: getExchangeBetEditSuccessfullEvents as TaggingBuilder,
  [NETWORK__PLACE_SBK_BET_SUCCESS]: getSportsbookSuccessPlaceBetsEvents as TaggingBuilder,
  [UI__BETSLIP_OPEN]: getOpenBetslipEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_REMOVE_POTENTIAL_SELECTION]: getBetslipExchangeRemovePotentialSelectionEvent as TaggingBuilder,
  [UI__BETSLIP_SBK_REMOVE_POTENTIAL_SELECTION]: getBetslipSportsbookRemovePotentialSelectionEvent as TaggingBuilder,
  [UI__MARKET_EXC_BET_BUTTON_CLICK]: getExchangeAddSelectionToBetslip as TaggingBuilder,
  [BETTING__SBK_ADD_SELECTION_TAGGING]: getSportsbookAddSelectionToBetslip as TaggingBuilder,
  [FIRST_DEPOSIT_SUCCESS]: getFirstDepositSuccessEvent as TaggingBuilder,
  [DEPOSIT_SUCCESS]: getDepositSuccessEvent as TaggingBuilder,
  [DEPOSIT_FLOW]: getDepositFlowEvent as TaggingBuilder,
  [UI__BETSLIP_EXC_REMOVE_POTENTIAL_BET_CLICK]: getBetslipExchangeRemovePotentialBetClickEvent as TaggingBuilder,
  [UI__GENEROSITY_WALLET_BUTTON_CLICK]: getGenerosityWalletClick as TaggingBuilder,
  [UI__GENEROSITY_WALLET_CLOSE_CLICK]: getGenerosityWalletCloseEvent as TaggingBuilder,
  [BETTING__SPORTSBOOK_GENEROSITY_WALLET_BET_ACTION]: getGenerosityWalletBetslipClickAction as TaggingBuilder,
  [UI__FREE_BETS_WALLET_TOGGLE_CLICK]: getFreeBetsWalletToggleEvent as TaggingBuilder,
  [UI__NAVIGATE_GENEROSITY_WALLET_HELP]: getGenerosityWalletHelpClickEvent as TaggingBuilder,
  [UI__NAVIGATE_GENEROSITY_PAGE]: getGenerosityPageNavigation as TaggingBuilder,
  [UI__GENEROSITY_WALLET_PEBBLE_CLICK]: getGenerosityWalletPebbleClickEvent as TaggingBuilder,
  [OBB_CARD__EVENT_SELECTION]: getObbSelectionsEvents as TaggingBuilder,
  [OBB_CARD_GROUP__SECTION_TOGGLED]: getObbSectionToggledEvent as TaggingBuilder,
  [OBB_CARD_GROUP__LAYOUT_SELECTION]: getObbLayoutToggledEvent as TaggingBuilder,
  [OBB_CARD_GROUP__SHOW_MORE_CLICKED]: getObbShowMoreClickedEvent as TaggingBuilder,
  [BETTING__OBB_TOGGLE_LEG_ACTION]: getObbToggleLegEvent as TaggingBuilder,
  [BETTING__OBB_TOGGLE_MULTIPLE_LEG_ACTION]: getObbToggleMultipleLegEvent as TaggingBuilder,
  [BETTING__OBB_PLACE_FAILED_UPDATE]: getObbFailedPlaceBetEvent as TaggingBuilder,
  [NETWORK__OBB_PLACE_BET_SUCCESS]: getObbPlaceBetSuccessEvent as TaggingBuilder,
  [UI__ACTION_CONFIRMATION]: getOpenClearBetslipEvent as TaggingBuilder,
  [BETTING__OBB_SBK_KEEP_ACTION]: getRefuseConfirmationEvent as TaggingBuilder,
  [BETTING__OBB_SBK_CLEAR_ACTION]: getAcceptConfirmationEvent as TaggingBuilder,
  [BETTING__SPORTSBOOK_REMOVE_ALL_FREE_BETS_WALLETS_ACTION]: getRemoveGenerosityWalletEvent as TaggingBuilder,
  [UI__GENEROSITY_WALLET_APPLY_BUTTON_CLICK]: getGenerosityWalletApplyButtonClickEvent as TaggingBuilder,
  [UI__GENEROSITY_WALLET_REMOVE_CLICK]: getRemoveGenerosityWalletEvent as TaggingBuilder,
  [HAMBURGER_MENU_OPEN]: getHamburgerMenuOpenEvent as TaggingBuilder,
  [HAMBURGER_MENU_CLOSE]: getHamburgerMenuCloseEvent as TaggingBuilder,
  [UI__MARKET_BLURB_LINK_CLICK]: getMarketBlurbLinkClickEvent as TaggingBuilder,
  [UI__SQUAD_BET_PLAYER_PICKER_OPEN]: getEditSquadOpenEvent as TaggingBuilder,
  [UI__OBB_ENHANCED_TRACKING_PLAYER_COUNTER]: getObbEnhancedPlayerCounterEvent as TaggingBuilder,
  [UI__CLOSE_PLAYER_PICKER_MODAL]: getClosePlayerPickerModalEvent as TaggingBuilder,
  [UI__SQUAD_BET_PLAYER_PICKER_REMOVE_SQUAD_PARTICIPANT]:
    getSquadBetPlayerPickerRemoveSquadParticipantEvent as TaggingBuilder,
  [UI__TOGGLE_SQUAD_BET_PLAYER_PICKER_SQUAD_PARTICIPANT]:
    getSquadBetPlayerPickerToggleSquadParticipantEvent as TaggingBuilder,
  [UI__SQUAD_BET_PLAYER_PICKER_BET_BUTTON_CLICK]: getSquadBetPlayerPickerBetButtonClickEvent as TaggingBuilder,
  [UI__MY_BETS_SBK_ADD_PREVIOUS_SELECTIONS_CLICK]: getMyBetsReAddSelectionsEvent as TaggingBuilder,
  [UI__SMART_APP_BANNER_CLICK]: getSmartAppBannerClickEvent as TaggingBuilder,
  [UI__SMART_APP_BANNER_CLOSE]: getSmartAppBannerCloseEvent as TaggingBuilder,
  [UI__SMART_APP_BANNER_DISPLAY]: getSmartAppBannerDisplayEvent as TaggingBuilder,
  [UI__FAVOURITE_MARKETS_LIMIT_REACHED_MESSAGE_CLOSE]:
    getFavouriteMarketsLimitReachedMessageCloseEvent as TaggingBuilder,
  [UI__FAVOURITE_MARKETS_TOGGLE_FAVOURITE]: getFavouriteMarketsToggleFavouriteEvent as TaggingBuilder,
  [UI__FAVOURITE_MARKETS_TOOLTIP_CLOSE]: getFavouriteMarketsTooltipCloseEvent as TaggingBuilder,
  [UI__OBB_CREATED_BETS_LINK_CLICKED]: getObbCreatedBetsLinkClickEvent as TaggingBuilder,
  [UI__SQUAD_VS_SQUAD_TOGGLE_PLAYERS_TOOLTIP]: getToggleSquadVsSquadPlayersTooltipEvent as TaggingBuilder,
  [UI__NAVIGATE_SETTLEMENTLINK]: getSettlementLinkNavigation as TaggingBuilder,
  [UI__BETSLIP_SLIDER_INTERACTION]: getBetslipSliderInteractionEvent as TaggingBuilder,
  [UI__BETSLIP_SLIDER_DISPLAYED]: getBetslipSliderDisplayedEvent as TaggingBuilder,
  [OBB_EVENT_POPULARS_CARD__SHOW_MORE_CLICKED]: getObbEventPopularsShowMoreEvent as TaggingBuilder,
  [OBB_ONBOARDING_CARDS__CARD_GROUP_SWIPED]: getObbOnboardingCardsCardGroupSwipeEvent as TaggingBuilder,
  [OBB_ONBOARDING_CARDS__CARD_GROUP_DISPLAYED]: getObbOnboardingCardsCardGroupDisplayedEvent as TaggingBuilder,
};

/**
 * Retrieves an event builder based on the provided action type.
 * @param {ActionTypes} action - The action type used to fetch the event builder.
 * @param {ApplicationState} state - The current application state.
 * @returns {(TaggingTypes | undefined)} Returns the constructed tagging event or undefined if no event builder is found.
 */
function getEventBuilder(action: ActionTypes, state: ApplicationState) {
  const eventBuilder = ACTION_TAGGING_MAPPER[action.type];

  if (eventBuilder) {
    return eventBuilder(action, state);
  }

  return undefined;
}

export const createTaggingMiddleware =
  (sendEvent: (event: unknown) => void): Middleware<Record<string, never>, ApplicationState> =>
  ({ getState }) =>
  (next) =>
  async (action: ActionTypes) => {
    try {
      const events = getEventBuilder(action, getState());
      if (!events) return next(action);

      const eventsArray = Array.isArray(events) ? events : [events];

      eventsArray.forEach((event) => {
        if (event) {
          sendEvent(event);
        }
      });
    } catch (error) {
      console.error("Tagging Middleware error", error);
    }
    return next(action);
  };
