/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  condensed: string;
  matchTimeline: string;
  prematch: string;
  teamCrest: string;
  teamCrests: string;
  timeline: string;
  timelineContainer: string;
  timelines: string;
}
export const cssExports: CssExports;
export default cssExports;
