require_relative "lib/helpers"

default_platform(:android)

platform :android do
  before_all do |lane|
    if lane != :inhouseDeployFirebase && lane != :inhouseDebugDeployFirebase && lane!=:buildAndDeployArtifactoryApp && lane!=:buildReleaseBundle && lane !=:deployStoreApp && lane !=:deployFirebaseApp && lane !=:deployAWS
      gradle(task: "clean")
    end
  end

  after_each do |lane|
    if lane != :inhouseDeployFirebase && lane != :inhouseDebugDeployFirebase && lane!=:buildAndDeployArtifactoryApp && lane!=:buildReleaseBundle && lane !=:deployStoreApp && lane !=:deployFirebaseApp && lane !=:deployAWS
      reset_git_repo(
        force: true,
        files: [
          "../android/**/res/**/ic_launcher.png",
          "../android/**/res/**/ic_launcher_round.png"
        ]
      )
    end
  end

  # # TODO on Jira Ticket WISHTHK-213
  # desc "Builds the store app and deploys to artifactory"
  # lane :buildAndDeployArtifactoryApp do |options|
  #   # changes push notifications environment to production
  #   # keys / secrets can be found on company https://www.airship.com/ account
  #   set_properties_value(
  #     path: "./app/src/main/assets/airshipconfig.properties",
  #     key: "inProduction",
  #     value: true
  #   )
  #   set_properties_value(
  #     path: "./app/src/main/assets/airshipconfig.properties",
  #     key: "productionAppKey",
  #     value: "JAzbLoGdRVSK5rgvXn4sgw"
  #   )
  #   set_properties_value(
  #     path: "./app/src/main/assets/airshipconfig.properties",
  #     key: "productionAppSecret",
  #     value: "AcTn45eiRySedJ4akefKJw"
  #   )

  #   gradle(task: "assemblePlayRelease")
  # end

  desc "Builds the store app (aab)"
  lane :buildReleaseBundle do |options|
    # changes push notifications environment to production
    # keys / secrets can be found on company https://www.airship.com/ account
    set_properties_value(
      path: "./app/src/main/assets/airshipconfig.properties",
      key: "inProduction",
      value: true
    )
    set_properties_value(
      path: "./app/src/main/assets/airshipconfig.properties",
      key: "productionAppKey",
      value: "JAzbLoGdRVSK5rgvXn4sgw"
    )
    set_properties_value(
      path: "./app/src/main/assets/airshipconfig.properties",
      key: "productionAppSecret",
      value: "AcTn45eiRySedJ4akefKJw"
    )

    gradle(task: "bundlePlayRelease")
  end

  # desc "Deploys to firebase (apk)"
  # lane :deployFirebaseApp do
  #   firebase_app_distribution(
  #     app: "1:237660054779:android:264b95c0f4fd4857547c5e",
  #     android_artifact_type: "APK",
  #     android_artifact_path: "android_release-"  + ENV['RELEASE_BUILD_NUMBER'] + ".apk",
  #     groups: 'bfrb-teams',
  #     release_notes: "App target: Release: \n" + get_release_notes(),
  #     firebase_cli_token: ENV['FIREBASE_CI_KEY'],
  #     debug: true
  #   )
  # end

  desc "Deploys to play store (Internal track)"
  lane :deployStoreApp do |options|
    upload_to_play_store(
      **options,
      package_name: "com.skybet.app.skybet",
      aab: "android_sbg_release-"  + ENV['RELEASE_BUILD_NUMBER'] + ".aab",
      skip_upload_apk: true,
      track: "internal",
      release_status: "draft",
      changes_not_sent_for_review: true
    )
  end

  # desc "Deploys to AWS - DEV / PRD"
  # lane :deployAWS do |options|
  #   aws_s3(
  #     access_key: ENV['AWS_ACCESS_KEY_ID'],
  #     secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  #     bucket: ENV['AWS_BUCKET'],
  #     region: ENV['AWS_DEFAULT_REGION'],
  #     # Depending on the jenkins choice, deploy a versioned apk or a production ready apk
  #     apk:  ENV['DEPLOY_ENV_PARAM'] == "DEV" ? "android_release-" + ENV['RELEASE_BUILD_NUMBER'] + ".apk" : "betfair-sports-betting.apk",
  #     acl: "bucket-owner-full-control",
  #     path: 'android/',
  #     upload_metadata: false
  #   )
  # end

  desc "Upload our In-House app to Firebase on CI for the stakeholders"
  lane :inhouseDeployFirebase do
    firebase_app_distribution(
      app: "1:471098256672:android:ec70c902bfe065a0b83b45",
      apk_path: "app/build/outputs/apk/play/inhouse/SkyBet-" + ENV['BUILD_NUMBER'] + ".apk",
      groups: 'sbgtbd-teams',
      release_notes: "App target: Play \n" + get_release_notes_from_file(),
      firebase_cli_token: ENV['FIREBASE_CI_KEY'],
      debug: true
    )
  end

  desc "Upload our QA apps to Firebase on CI for the stakeholders"
  lane :inhouseDebugDeployFirebase do
    firebase_app_distribution(
      app: "1:471098256672:android:7008f8c44aeda18cb83b45",
      apk_path: "app/build/outputs/apk/play/debug/app-play-debug.apk",
      groups: 'sbgtbd-teams',
      release_notes: "App target: Play \n" + get_release_notes_from_file(),
      firebase_cli_token: ENV['FIREBASE_CI_KEY'],
      debug: true
    )
  end
end
