/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionContainer: string;
  headline: string;
  promotionAction: string;
  promotionBody: string;
  promotionCard: string;
  promotionContainer: string;
  promotionFooter: string;
  promotionImage: string;
  promotionImageContainer: string;
  promotionInfoContainer: string;
  promotionTitles: string;
  subtitle: string;
  summary: string;
  title: string;
  titleEnd: string;
}
export const cssExports: CssExports;
export default cssExports;
