/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  emptySpace: string;
  playerName: string;
  playerNameAndTeamContainer: string;
  tableHeaderText: string;
  tableRow: string;
  teamName: string;
  total: string;
  verticalAlignMiddle: string;
}
export const cssExports: CssExports;
export default cssExports;
