/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  description: string;
  football: string;
  horseRacing: string;
  imageContainer: string;
  informationContainer: string;
  leftColumn: string;
  square: string;
  virtualRunnerInnerContainer: string;
  virtualRunnerLine: string;
  virtualRunnerNumber: string;
}
export const cssExports: CssExports;
export default cssExports;
