/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  gameContainer: string;
  overlayGaming: string;
  overlayGamingDesktop: string;
  pinGamingSearch: string;
  rectangleResult: string;
  resultsContainer: string;
  searchBarHidden: string;
  searchBarVisible: string;
}
export const cssExports: CssExports;
export default cssExports;
