/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  alignCenter: string;
  alignLeft: string;
  alignRight: string;
  clockContainer: string;
  clockInline: string;
  clockText: string;
  clockWithText: string;
  collapsable: string;
  collapseContentSections: string;
  groupLinks: string;
  image: string;
  imageContainer: string;
  largeImage: string;
  link: string;
  quickLinksList: string;
  reverse: string;
  section: string;
  sectionTitle: string;
  session: string;
  shadow: string;
  text: string;
  title: string;
  unreadNotifications: string;
  userDetails: string;
}
export const cssExports: CssExports;
export default cssExports;
