/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  centerText: string;
  combinationsGrid: string;
  combinationsList: string;
  content: string;
  contentCell: string;
  header: string;
  headerCell: string;
  headerClosed: string;
  headerId: string;
  headerOdd: string;
  headerPayout: string;
  headerPayoutClosed: string;
  headerTitle: string;
  headerTitleContainer: string;
  icon: string;
  iconSize: string;
  id: string;
  line: string;
  lines: string;
  moreButton: string;
  moreIcon: string;
  odd: string;
  payout: string;
  withoutMore: string;
}
export const cssExports: CssExports;
export default cssExports;
