/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButton: string;
  linkTag: string;
  oddsBoostTag: string;
  promoDescriptionContainer: string;
  promotionAction: string;
  promotionBody: string;
  promotionCard: string;
  promotionCardLink: string;
  promotionContent: string;
  promotionFooter: string;
  promotionHeader: string;
  promotionHeaderContent: string;
  promotionImage: string;
  promotionImageContainer: string;
  promotionOverlay: string;
  promotionSummary: string;
  promotionTermsAndConditions: string;
  promotionTermsAndConditionsLabel: string;
  promotionTermsAndConditionsLink: string;
}
export const cssExports: CssExports;
export default cssExports;
