/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badgeText: string;
  customLogoContainer: string;
  gameBadgeContainer: string;
  gameCopyright: string;
  gameInfoContainer: string;
  gameTextButtonContainer: string;
  gameTextContainer: string;
  gameTile: string;
  gameTitle: string;
  gameWidgetTile: string;
  iconBackground: string;
  imgGreyBorder: string;
  imgRedBorder: string;
  isNewDecorated: string;
  jackpotLogoContainer: string;
  jackpotTile: string;
  label: string;
  round: string;
  singleImage: string;
  tileGradient: string;
  xmall: string;
}
export const cssExports: CssExports;
export default cssExports;
