/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  promoCard: string;
  promoCardContent: string;
  sliderTooltipContainer: string;
  subheader: string;
}
export const cssExports: CssExports;
export default cssExports;
