/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bspAdvantage: string;
  bspAdvantageLabel: string;
  container: string;
  infoWrapper: string;
  winningAndBspTitle: string;
  winningTime: string;
  winningTimeLabel: string;
}
export const cssExports: CssExports;
export default cssExports;
