###############################
# MockServer & Proxy Settings #
###############################

# Socket & Port Settings

# socket timeout in milliseconds (default 120000)
mockserver.maxSocketTimeout=120000

mockserver.disableSystemOut=true

mockserver.logLevel=INFO
mockserver.attemptToProxyIfNoMatchingExpectation=true

mockserver.maxExpectations=100
mockserver.maxLogEntries=2000
mockserver.maxWebSocketExpectations=100

# mockserver.nioEventLoopThreadCount=35 # Default: maximum of 35 or available processors count
# mockserver.actionHandlerThreadCount=20 # maximum of 20 or available processors count
# mockserver.webSocketClientEventLoopThreadCount=5 # Default: 5