/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betSegmentInfo: string;
  bog: string;
  buttonsContainer: string;
  container: string;
  containerBody: string;
  headerContainer: string;
  statusLabelContainer: string;
  subtitle: string;
  supportingText: string;
  supportingTextContainer: string;
  title: string;
  titleIndicatorsContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
