/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  blurbContainer: string;
  cardContainer: string;
  cardContent: string;
  desktopView: string;
  sbkPlacePanel: string;
  scrollable: string;
  scrollableDesktop: string;
}
export const cssExports: CssExports;
export default cssExports;
