/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backgroundDiamonds: string;
  content: string;
  diamond: string;
  hotStatus: string;
  jackpotItem: string;
  jackpotMerchandiseContainer: string;
  jackpots: string;
  logo: string;
  logoImg: string;
}
export const cssExports: CssExports;
export default cssExports;
