/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  arrow: string;
  arrowContainer: string;
  carouselContainer: string;
  carouselItem: string;
  carouselSlider: string;
  itemImages: string;
  left: string;
  progress: string;
  progressBar: string;
  progressBarContainer: string;
  right: string;
  shadowBox: string;
  shadowBoxTop: string;
}
export const cssExports: CssExports;
export default cssExports;
