/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonContainer: string;
  buttonContainerFlex: string;
  favoriteButton: string;
  favoriteButtonContainer: string;
  gameInfoContainer: string;
  gameInfowWrapper: string;
  howToPlayDetails: string;
  infoContainer: string;
  infoHeadlineTitle: string;
  keyInfoSection: string;
  table: string;
  tableContent: string;
  tableHeader: string;
  tableTitle: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
