/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  headerContainer: string;
  headerFadeOut: string;
  headerShadow: string;
  hidePortalContainer: string;
  portalsContainer: string;
  portalsContainerWithSearch: string;
}
export const cssExports: CssExports;
export default cssExports;
