/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  alignTextRight: string;
  container: string;
  distanceLabel: string;
  dnfCode: string;
  dnfCodesContainer: string;
  dnfIcon: string;
  dnfItem: string;
  dnfsBoard: string;
  drawNumber: string;
  fav: string;
  headerText: string;
  horseInfoContainer: string;
  horseInformation: string;
  horseInformationWrapper: string;
  infoIcon: string;
  jockeyName: string;
  leftColumn: string;
  positionLabel: string;
  ranLabel: string;
  resultsTable: string;
  runnerContainer: string;
  saddleCloth: string;
  silk: string;
  silkContainer: string;
  startingPriceLabel: string;
  tableInfo: string;
  textOverflow: string;
  title: string;
  trainerName: string;
  winnerRibbonContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
