/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  headerAndScrollableContainer: string;
  leftSideBar: string;
  mainContainer: string;
  rightSideBar: string;
  scrollable: string;
  scrollableSectionDesktop: string;
  scrollbarContainer: string;
  sectionsContainer: string;
  sideBar: string;
  stickyContainer: string;
  webWrappedVersion: string;
}
export const cssExports: CssExports;
export default cssExports;
