/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betslipCollapsed: string;
  fullHeightContainer: string;
  overlay: string;
  overlayFadeOut: string;
  overlayed: string;
  scrollable: string;
  scrollableFadeOut: string;
  webWrappedVersion: string;
}
export const cssExports: CssExports;
export default cssExports;
