/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accountContainer: string;
  accountContainersGroup: string;
  accountHeader: string;
  backButton: string;
  balanceContainer: string;
  balanceLabel: string;
  generosityWalletActionContainer: string;
  header: string;
  loginContainer: string;
  logoContainer: string;
  logoLink: string;
  menuButton: string;
  notificationIconContainer: string;
  userIconContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
