/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  keyboardContainer: string;
  notificationsListContainer: string;
  quickStakesContainer: string;
  scrollableBetslip: string;
  scrollableBetslipDesktop: string;
}
export const cssExports: CssExports;
export default cssExports;
