/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  center: string;
  firstName: string;
  jersey: string;
  jerseyContainer: string;
  jerseyContainerBackground: string;
  jerseyLarge: string;
  lastName: string;
  level1: string;
  level2: string;
  level3: string;
  microPlayer: string;
  microPlayerWrapper: string;
  multiVariant: string;
  multipleFirstName: string;
  multipleLastName: string;
  multiplePlayers: string;
  nameContainer: string;
  nameEmptyState: string;
  pair: string;
  playersDisabledLabel: string;
  posLeft: string;
  posRight: string;
  removePlayerButton: string;
  removePlayerContainer: string;
  removePlayerTouchContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
