// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LiveGameData } from "./LiveGameData";
import {
  LiveGameDataFromJSON,
  LiveGameDataFromJSONTyped,
  LiveGameDataToJSON,
  LiveGameDataToJSONTyped,
} from "./LiveGameData";

/**
 *
 * @export
 * @interface AccaFreezeLegEligibility
 */
export interface AccaFreezeLegEligibility {
  /**
   *
   * @type {LiveGameData}
   * @memberof AccaFreezeLegEligibility
   */
  gameDetails?: LiveGameData;
}

/**
 * Check if a given object implements the AccaFreezeLegEligibility interface.
 */
export function instanceOfAccaFreezeLegEligibility(value: object): value is AccaFreezeLegEligibility {
  return true;
}

export function AccaFreezeLegEligibilityFromJSON(json: any): AccaFreezeLegEligibility {
  return AccaFreezeLegEligibilityFromJSONTyped(json, false);
}

export function AccaFreezeLegEligibilityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AccaFreezeLegEligibility {
  if (json == null) {
    return json;
  }
  return {
    gameDetails: json["gameDetails"] == null ? undefined : LiveGameDataFromJSON(json["gameDetails"]),
  };
}

export function AccaFreezeLegEligibilityToJSON(json: any): AccaFreezeLegEligibility {
  return AccaFreezeLegEligibilityToJSONTyped(json, false);
}

export function AccaFreezeLegEligibilityToJSONTyped(
  value?: AccaFreezeLegEligibility | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    gameDetails: LiveGameDataToJSON(value["gameDetails"]),
  };
}
