// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LiveGameData } from "./LiveGameData";
import {
  LiveGameDataFromJSON,
  LiveGameDataFromJSONTyped,
  LiveGameDataToJSON,
  LiveGameDataToJSONTyped,
} from "./LiveGameData";

/**
 *
 * @export
 * @interface AccaFreezeLegDetails
 */
export interface AccaFreezeLegDetails {
  /**
   *
   * @type {LiveGameData}
   * @memberof AccaFreezeLegDetails
   */
  freezeDetails?: LiveGameData;
}

/**
 * Check if a given object implements the AccaFreezeLegDetails interface.
 */
export function instanceOfAccaFreezeLegDetails(value: object): value is AccaFreezeLegDetails {
  return true;
}

export function AccaFreezeLegDetailsFromJSON(json: any): AccaFreezeLegDetails {
  return AccaFreezeLegDetailsFromJSONTyped(json, false);
}

export function AccaFreezeLegDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccaFreezeLegDetails {
  if (json == null) {
    return json;
  }
  return {
    freezeDetails: json["freezeDetails"] == null ? undefined : LiveGameDataFromJSON(json["freezeDetails"]),
  };
}

export function AccaFreezeLegDetailsToJSON(json: any): AccaFreezeLegDetails {
  return AccaFreezeLegDetailsToJSONTyped(json, false);
}

export function AccaFreezeLegDetailsToJSONTyped(
  value?: AccaFreezeLegDetails | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    freezeDetails: LiveGameDataToJSON(value["freezeDetails"]),
  };
}
