// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BetEligibility } from "./BetEligibility";
import {
  BetEligibilityFromJSON,
  BetEligibilityFromJSONTyped,
  BetEligibilityToJSON,
  BetEligibilityToJSONTyped,
} from "./BetEligibility";

/**
 *
 * @export
 * @interface BetEligibilityResponse
 */
export interface BetEligibilityResponse {
  /**
   *
   * @type {Array<BetEligibility>}
   * @memberof BetEligibilityResponse
   */
  betEligibilities?: Array<BetEligibility>;
}

/**
 * Check if a given object implements the BetEligibilityResponse interface.
 */
export function instanceOfBetEligibilityResponse(value: object): value is BetEligibilityResponse {
  return true;
}

export function BetEligibilityResponseFromJSON(json: any): BetEligibilityResponse {
  return BetEligibilityResponseFromJSONTyped(json, false);
}

export function BetEligibilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetEligibilityResponse {
  if (json == null) {
    return json;
  }
  return {
    betEligibilities:
      json["betEligibilities"] == null
        ? undefined
        : (json["betEligibilities"] as Array<any>).map(BetEligibilityFromJSON),
  };
}

export function BetEligibilityResponseToJSON(json: any): BetEligibilityResponse {
  return BetEligibilityResponseToJSONTyped(json, false);
}

export function BetEligibilityResponseToJSONTyped(
  value?: BetEligibilityResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    betEligibilities:
      value["betEligibilities"] == null
        ? undefined
        : (value["betEligibilities"] as Array<any>).map(BetEligibilityToJSON),
  };
}
