// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BetMutationEligibility } from "./BetMutationEligibility";
import {
  BetMutationEligibilityFromJSON,
  BetMutationEligibilityFromJSONTyped,
  BetMutationEligibilityToJSON,
  BetMutationEligibilityToJSONTyped,
} from "./BetMutationEligibility";
import type { LegEligibility } from "./LegEligibility";
import {
  LegEligibilityFromJSON,
  LegEligibilityFromJSONTyped,
  LegEligibilityToJSON,
  LegEligibilityToJSONTyped,
} from "./LegEligibility";

/**
 *
 * @export
 * @interface BetEligibility
 */
export interface BetEligibility {
  /**
   *
   * @type {string}
   * @memberof BetEligibility
   */
  betId?: string;
  /**
   *
   * @type {Array<BetMutationEligibility>}
   * @memberof BetEligibility
   */
  betMutationEligibility?: Array<BetMutationEligibility>;
  /**
   *
   * @type {Array<LegEligibility>}
   * @memberof BetEligibility
   */
  legs?: Array<LegEligibility>;
}

/**
 * Check if a given object implements the BetEligibility interface.
 */
export function instanceOfBetEligibility(value: object): value is BetEligibility {
  return true;
}

export function BetEligibilityFromJSON(json: any): BetEligibility {
  return BetEligibilityFromJSONTyped(json, false);
}

export function BetEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetEligibility {
  if (json == null) {
    return json;
  }
  return {
    betId: json["betId"] == null ? undefined : json["betId"],
    betMutationEligibility:
      json["betMutationEligibility"] == null
        ? undefined
        : (json["betMutationEligibility"] as Array<any>).map(BetMutationEligibilityFromJSON),
    legs: json["legs"] == null ? undefined : (json["legs"] as Array<any>).map(LegEligibilityFromJSON),
  };
}

export function BetEligibilityToJSON(json: any): BetEligibility {
  return BetEligibilityToJSONTyped(json, false);
}

export function BetEligibilityToJSONTyped(value?: BetEligibility | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    betId: value["betId"],
    betMutationEligibility:
      value["betMutationEligibility"] == null
        ? undefined
        : (value["betMutationEligibility"] as Array<any>).map(BetMutationEligibilityToJSON),
    legs: value["legs"] == null ? undefined : (value["legs"] as Array<any>).map(LegEligibilityToJSON),
  };
}
