// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BetMutationEligibilityType = {
  AccaFreeze: "AccaFreeze",
  None: "None",
} as const;
export type BetMutationEligibilityType = (typeof BetMutationEligibilityType)[keyof typeof BetMutationEligibilityType];

export function instanceOfBetMutationEligibilityType(value: any): boolean {
  for (const key in BetMutationEligibilityType) {
    if (Object.prototype.hasOwnProperty.call(BetMutationEligibilityType, key)) {
      if (BetMutationEligibilityType[key as keyof typeof BetMutationEligibilityType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function BetMutationEligibilityTypeFromJSON(json: any): BetMutationEligibilityType {
  return BetMutationEligibilityTypeFromJSONTyped(json, false);
}

export function BetMutationEligibilityTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BetMutationEligibilityType {
  return json as BetMutationEligibilityType;
}

export function BetMutationEligibilityTypeToJSON(value?: BetMutationEligibilityType | null): any {
  return value as any;
}

export function BetMutationEligibilityTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): BetMutationEligibilityType {
  return value as BetMutationEligibilityType;
}
