// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BetMutationEligibilityType } from "./BetMutationEligibilityType";
import {
  BetMutationEligibilityTypeFromJSON,
  BetMutationEligibilityTypeFromJSONTyped,
  BetMutationEligibilityTypeToJSON,
  BetMutationEligibilityTypeToJSONTyped,
} from "./BetMutationEligibilityType";

/**
 *
 * @export
 * @interface BetMutationEligibility
 */
export interface BetMutationEligibility {
  /**
   *
   * @type {BetMutationEligibilityType}
   * @memberof BetMutationEligibility
   */
  mutation?: BetMutationEligibilityType;
  /**
   *
   * @type {string}
   * @memberof BetMutationEligibility
   */
  promoCode?: string;
}

/**
 * Check if a given object implements the BetMutationEligibility interface.
 */
export function instanceOfBetMutationEligibility(value: object): value is BetMutationEligibility {
  return true;
}

export function BetMutationEligibilityFromJSON(json: any): BetMutationEligibility {
  return BetMutationEligibilityFromJSONTyped(json, false);
}

export function BetMutationEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetMutationEligibility {
  if (json == null) {
    return json;
  }
  return {
    mutation: json["mutation"] == null ? undefined : BetMutationEligibilityTypeFromJSON(json["mutation"]),
    promoCode: json["promoCode"] == null ? undefined : json["promoCode"],
  };
}

export function BetMutationEligibilityToJSON(json: any): BetMutationEligibility {
  return BetMutationEligibilityToJSONTyped(json, false);
}

export function BetMutationEligibilityToJSONTyped(
  value?: BetMutationEligibility | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    mutation: BetMutationEligibilityTypeToJSON(value["mutation"]),
    promoCode: value["promoCode"],
  };
}
