// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LegAvailabilityDetail = {
  Available: "Available",
  Unavailable: "Unavailable",
  Suspended: "Suspended",
} as const;
export type LegAvailabilityDetail = (typeof LegAvailabilityDetail)[keyof typeof LegAvailabilityDetail];

export function instanceOfLegAvailabilityDetail(value: any): boolean {
  for (const key in LegAvailabilityDetail) {
    if (Object.prototype.hasOwnProperty.call(LegAvailabilityDetail, key)) {
      if (LegAvailabilityDetail[key as keyof typeof LegAvailabilityDetail] === value) {
        return true;
      }
    }
  }
  return false;
}

export function LegAvailabilityDetailFromJSON(json: any): LegAvailabilityDetail {
  return LegAvailabilityDetailFromJSONTyped(json, false);
}

export function LegAvailabilityDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegAvailabilityDetail {
  return json as LegAvailabilityDetail;
}

export function LegAvailabilityDetailToJSON(value?: LegAvailabilityDetail | null): any {
  return value as any;
}

export function LegAvailabilityDetailToJSONTyped(value: any, ignoreDiscriminator: boolean): LegAvailabilityDetail {
  return value as LegAvailabilityDetail;
}
