// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LegMutationDetails } from "./LegMutationDetails";
import {
  LegMutationDetailsFromJSON,
  LegMutationDetailsFromJSONTyped,
  LegMutationDetailsToJSON,
  LegMutationDetailsToJSONTyped,
} from "./LegMutationDetails";
import type { LegMutationEligibility } from "./LegMutationEligibility";
import {
  LegMutationEligibilityFromJSON,
  LegMutationEligibilityFromJSONTyped,
  LegMutationEligibilityToJSON,
  LegMutationEligibilityToJSONTyped,
} from "./LegMutationEligibility";

/**
 *
 * @export
 * @interface LegEligibility
 */
export interface LegEligibility {
  /**
   *
   * @type {string}
   * @memberof LegEligibility
   */
  legRef?: string;
  /**
   *
   * @type {Array<LegMutationEligibility>}
   * @memberof LegEligibility
   */
  legMutationEligibility?: Array<LegMutationEligibility>;
  /**
   *
   * @type {Array<LegMutationDetails>}
   * @memberof LegEligibility
   */
  legMutationDetails?: Array<LegMutationDetails>;
}

/**
 * Check if a given object implements the LegEligibility interface.
 */
export function instanceOfLegEligibility(value: object): value is LegEligibility {
  return true;
}

export function LegEligibilityFromJSON(json: any): LegEligibility {
  return LegEligibilityFromJSONTyped(json, false);
}

export function LegEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegEligibility {
  if (json == null) {
    return json;
  }
  return {
    legRef: json["legRef"] == null ? undefined : json["legRef"],
    legMutationEligibility:
      json["legMutationEligibility"] == null
        ? undefined
        : (json["legMutationEligibility"] as Array<any>).map(LegMutationEligibilityFromJSON),
    legMutationDetails:
      json["legMutationDetails"] == null
        ? undefined
        : (json["legMutationDetails"] as Array<any>).map(LegMutationDetailsFromJSON),
  };
}

export function LegEligibilityToJSON(json: any): LegEligibility {
  return LegEligibilityToJSONTyped(json, false);
}

export function LegEligibilityToJSONTyped(value?: LegEligibility | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    legRef: value["legRef"],
    legMutationEligibility:
      value["legMutationEligibility"] == null
        ? undefined
        : (value["legMutationEligibility"] as Array<any>).map(LegMutationEligibilityToJSON),
    legMutationDetails:
      value["legMutationDetails"] == null
        ? undefined
        : (value["legMutationDetails"] as Array<any>).map(LegMutationDetailsToJSON),
  };
}
