// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccaFreezeLegEligibility } from "./AccaFreezeLegEligibility";
import {
  instanceOfAccaFreezeLegEligibility,
  AccaFreezeLegEligibilityFromJSON,
  AccaFreezeLegEligibilityFromJSONTyped,
  AccaFreezeLegEligibilityToJSON,
} from "./AccaFreezeLegEligibility";

/**
 * @type LegMutationEligibilityDetails
 *
 * @export
 */
export type LegMutationEligibilityDetails = AccaFreezeLegEligibility;

export function LegMutationEligibilityDetailsFromJSON(json: any): LegMutationEligibilityDetails {
  return LegMutationEligibilityDetailsFromJSONTyped(json, false);
}

export function LegMutationEligibilityDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LegMutationEligibilityDetails {
  if (json == null) {
    return json;
  }
  if (instanceOfAccaFreezeLegEligibility(json)) {
    return AccaFreezeLegEligibilityFromJSONTyped(json, true);
  }

  return {} as any;
}

export function LegMutationEligibilityDetailsToJSON(json: any): any {
  return LegMutationEligibilityDetailsToJSONTyped(json, false);
}

export function LegMutationEligibilityDetailsToJSONTyped(
  value?: LegMutationEligibilityDetails | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  if (instanceOfAccaFreezeLegEligibility(value)) {
    return AccaFreezeLegEligibilityToJSON(value as AccaFreezeLegEligibility);
  }

  return {};
}
