// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AccaFreezeLegDetails } from "./AccaFreezeLegDetails";
import {
  instanceOfAccaFreezeLegDetails,
  AccaFreezeLegDetailsFromJSON,
  AccaFreezeLegDetailsFromJSONTyped,
  AccaFreezeLegDetailsToJSON,
} from "./AccaFreezeLegDetails";

/**
 * @type LegMutationDetails
 *
 * @export
 */
export type LegMutationDetails = AccaFreezeLegDetails;

export function LegMutationDetailsFromJSON(json: any): LegMutationDetails {
  return LegMutationDetailsFromJSONTyped(json, false);
}

export function LegMutationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegMutationDetails {
  if (json == null) {
    return json;
  }
  if (instanceOfAccaFreezeLegDetails(json)) {
    return AccaFreezeLegDetailsFromJSONTyped(json, true);
  }

  return {} as any;
}

export function LegMutationDetailsToJSON(json: any): any {
  return LegMutationDetailsToJSONTyped(json, false);
}

export function LegMutationDetailsToJSONTyped(
  value?: LegMutationDetails | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  if (instanceOfAccaFreezeLegDetails(value)) {
    return AccaFreezeLegDetailsToJSON(value as AccaFreezeLegDetails);
  }

  return {};
}
