// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { LegMutationEligibilityDetails } from "./LegMutationEligibilityDetails";
import {
  LegMutationEligibilityDetailsFromJSON,
  LegMutationEligibilityDetailsFromJSONTyped,
  LegMutationEligibilityDetailsToJSON,
  LegMutationEligibilityDetailsToJSONTyped,
} from "./LegMutationEligibilityDetails";
import type { LegMutationType } from "./LegMutationType";
import {
  LegMutationTypeFromJSON,
  LegMutationTypeFromJSONTyped,
  LegMutationTypeToJSON,
  LegMutationTypeToJSONTyped,
} from "./LegMutationType";
import type { LegAvailabilityDetail } from "./LegAvailabilityDetail";
import {
  LegAvailabilityDetailFromJSON,
  LegAvailabilityDetailFromJSONTyped,
  LegAvailabilityDetailToJSON,
  LegAvailabilityDetailToJSONTyped,
} from "./LegAvailabilityDetail";

/**
 *
 * @export
 * @interface LegMutationEligibility
 */
export interface LegMutationEligibility {
  /**
   *
   * @type {LegMutationType}
   * @memberof LegMutationEligibility
   */
  mutation?: LegMutationType;
  /**
   *
   * @type {LegAvailabilityDetail}
   * @memberof LegMutationEligibility
   */
  mutationAvailability?: LegAvailabilityDetail;
  /**
   *
   * @type {LegMutationEligibilityDetails}
   * @memberof LegMutationEligibility
   */
  details?: LegMutationEligibilityDetails | null;
}

/**
 * Check if a given object implements the LegMutationEligibility interface.
 */
export function instanceOfLegMutationEligibility(value: object): value is LegMutationEligibility {
  return true;
}

export function LegMutationEligibilityFromJSON(json: any): LegMutationEligibility {
  return LegMutationEligibilityFromJSONTyped(json, false);
}

export function LegMutationEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegMutationEligibility {
  if (json == null) {
    return json;
  }
  return {
    mutation: json["mutation"] == null ? undefined : LegMutationTypeFromJSON(json["mutation"]),
    mutationAvailability:
      json["mutationAvailability"] == null ? undefined : LegAvailabilityDetailFromJSON(json["mutationAvailability"]),
    details: json["details"] == null ? undefined : LegMutationEligibilityDetailsFromJSON(json["details"]),
  };
}

export function LegMutationEligibilityToJSON(json: any): LegMutationEligibility {
  return LegMutationEligibilityToJSONTyped(json, false);
}

export function LegMutationEligibilityToJSONTyped(
  value?: LegMutationEligibility | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    mutation: LegMutationTypeToJSON(value["mutation"]),
    mutationAvailability: LegAvailabilityDetailToJSON(value["mutationAvailability"]),
    details: LegMutationEligibilityDetailsToJSON(value["details"]),
  };
}
