// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LegMutationType = {
  AccaFreeze: "AccaFreeze",
  None: "None",
} as const;
export type LegMutationType = (typeof LegMutationType)[keyof typeof LegMutationType];

export function instanceOfLegMutationType(value: any): boolean {
  for (const key in LegMutationType) {
    if (Object.prototype.hasOwnProperty.call(LegMutationType, key)) {
      if (LegMutationType[key as keyof typeof LegMutationType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function LegMutationTypeFromJSON(json: any): LegMutationType {
  return LegMutationTypeFromJSONTyped(json, false);
}

export function LegMutationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LegMutationType {
  return json as LegMutationType;
}

export function LegMutationTypeToJSON(value?: LegMutationType | null): any {
  return value as any;
}

export function LegMutationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LegMutationType {
  return value as LegMutationType;
}
