// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LiveGameData
 */
export interface LiveGameData {
  /**
   *
   * @type {number}
   * @memberof LiveGameData
   */
  minute?: number;
  /**
   *
   * @type {string}
   * @memberof LiveGameData
   */
  homeTeamName?: string;
  /**
   *
   * @type {number}
   * @memberof LiveGameData
   */
  homeTeamScore?: number;
  /**
   *
   * @type {string}
   * @memberof LiveGameData
   */
  awayTeamName?: string;
  /**
   *
   * @type {number}
   * @memberof LiveGameData
   */
  awayTeamScore?: number;
}

/**
 * Check if a given object implements the LiveGameData interface.
 */
export function instanceOfLiveGameData(value: object): value is LiveGameData {
  return true;
}

export function LiveGameDataFromJSON(json: any): LiveGameData {
  return LiveGameDataFromJSONTyped(json, false);
}

export function LiveGameDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveGameData {
  if (json == null) {
    return json;
  }
  return {
    minute: json["minute"] == null ? undefined : json["minute"],
    homeTeamName: json["homeTeamName"] == null ? undefined : json["homeTeamName"],
    homeTeamScore: json["homeTeamScore"] == null ? undefined : json["homeTeamScore"],
    awayTeamName: json["awayTeamName"] == null ? undefined : json["awayTeamName"],
    awayTeamScore: json["awayTeamScore"] == null ? undefined : json["awayTeamScore"],
  };
}

export function LiveGameDataToJSON(json: any): LiveGameData {
  return LiveGameDataToJSONTyped(json, false);
}

export function LiveGameDataToJSONTyped(value?: LiveGameData | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    minute: value["minute"],
    homeTeamName: value["homeTeamName"],
    homeTeamScore: value["homeTeamScore"],
    awayTeamName: value["awayTeamName"],
    awayTeamScore: value["awayTeamScore"],
  };
}
