/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  defaultContainer: string;
  gaming: string;
  noResultsLabel: string;
  noResultsLabelGaming: string;
  numberOfResultsLabel: string;
  outOfIdeasLabel: string;
  outOfIdeasLabelGaming: string;
  recommendedGamesContainer: string;
  recommendedGamesWrapper: string;
  searchBar: string;
  searchBarGaming: string;
  searchHistoryContainer: string;
  searchHistoryLabel: string;
  searchHistoryPebblesContainer: string;
  searchResultsContainer: string;
  searchResultsGamingContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
