/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButtonsContainer: string;
  defaultGap: string;
  entryPointGap: string;
  microPlayerContainer: string;
  outcomeLabel: string;
  squadsContainer: string;
  title: string;
  vsText: string;
}
export const cssExports: CssExports;
export default cssExports;
