/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  headerContainer: string;
  headerContainerDesktop: string;
  headerContainerSlideDown: string;
  headerFadeIn: string;
  overlay: string;
  overlaySlideIn: string;
  scrollableFadeIn: string;
}
export const cssExports: CssExports;
export default cssExports;
