/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  iconWrapper: string;
  lines: string;
  minute: string;
  player: string;
  reverse: string;
  wrapContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
