/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  editButtonContainer: string;
  notificationsListContainer: string;
  scrollableConfirm: string;
  scrollableConfirmDesktop: string;
}
export const cssExports: CssExports;
export default cssExports;
