/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  closeButton: string;
  modal: string;
  modalContainer: string;
  modalFooter: string;
  modalHeader: string;
  modalHeaderScrolled: string;
  modalTitle: string;
  overlay: string;
}
export const cssExports: CssExports;
export default cssExports;
