/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  incidentEventsWrapper: string;
  matchStats: string;
  matchTimelineDetails: string;
  matchTimelineWrapper: string;
  minuteByMinute: string;
  minuteByMinuteTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
