/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  boostedIcon: string;
  boostedIconContainer: string;
  bubbleItemsContainer: string;
  content: string;
  fixtureHeader: string;
  header: string;
  headerFixture: string;
  popularBetBuilderCard: string;
  selectionTypeIcon: string;
}
export const cssExports: CssExports;
export default cssExports;
