/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  image: string;
  imageContainer: string;
  large: string;
  small: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
