/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  away: string;
  card: string;
  goal: string;
  goalImage: string;
  goalImageAway: string;
  goalImageHome: string;
  home: string;
  ownGoal: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
