version: "3.4"
services:
  reverseproxy:
    image: ppb/tbdsbg/dev/reverseproxy-qa
    build:
      context: ${PWD}/../../../apps/sbg/reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/../../../apps/sbg/reverse-proxy/dev/webapp.d/qa.apitbdsbg-remote.locations.conf:/etc/nginx/conf.d/custom.locations.conf
      - ${PWD}/../../../apps/sbg/reverse-proxy/dev/webapp.d/qa.locations.conf:/etc/nginx/conf.d/locations.conf
      - ${PWD}/../../../apps/sbg/reverse-proxy/dev/webapp.d/qa.upstream:/etc/nginx/conf.d/qa.upstream
    depends_on:
      - http-webserver
      - webserver
volumes:
  tbd-assets:
