/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backIconContainer: string;
  balanceContainer: string;
  balanceLabel: string;
  closeIconContainer: string;
  freeBetsBalanceLabel: string;
  header: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
