/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  firstName: string;
  highlighted: string;
  labelDisabled: string;
  lastName: string;
  odds: string;
  placeholder: string;
  playerCardContainer: string;
  playerInfoContainer: string;
  playerNameContainer: string;
  playerStats: string;
  playerValuesContainer: string;
  position: string;
  statsContainer: string;
  statsDisabled: string;
  statsLabel: string;
  statsValue: string;
  supportingTextDisabled: string;
}
export const cssExports: CssExports;
export default cssExports;
