/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  budgetContent: string;
  container: string;
  linkContent: string;
  linkIcon: string;
  linkText: string;
  reset: string;
  supportingContent: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
