/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  closeButtonIconContainer: string;
  container: string;
  content: string;
  drawer: string;
  footerContent: string;
  header: string;
  headerContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
