/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  container: string;
  doubleCard: string;
  multiCardsLayout: string;
  singleCard: string;
}
export const cssExports: CssExports;
export default cssExports;
