/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  imageItem: string;
  linkItem: string;
  section: string;
  sessionItem: string;
  sessionItemLabel: string;
  sessionItemTime: string;
  textItem: string;
}
export const cssExports: CssExports;
export default cssExports;
