/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  desktopSticky: string;
  nonSticky: string;
  raceDetailsContainer: string;
  raceViewLink: string;
}
export const cssExports: CssExports;
export default cssExports;
