// @ts-nocheck OpenApi generated file. Please do no edit it!
/* tslint:disable */
/* eslint-disable */
/**
 * Bet Mutation Service - OpenAPI 3.0
 * Bet Mutation Service
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { BetEligibilityResponse } from "../models/index";
import { BetEligibilityResponseFromJSON, BetEligibilityResponseToJSON } from "../models/index";

export interface BetEligibilityRequest {
  betIds: Array<string>;
  xAUTHENTICATION?: string;
  ssoid?: string;
}

/**
 *
 */
export class BetMutationEligibilityServiceApi extends runtime.BaseAPI {
  /**
   * Get Bet Mutation Eligibility by Id
   * Get BetMutation Eligibility
   */
  async betEligibilityRaw(
    requestParameters: BetEligibilityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<BetEligibilityResponse>> {
    if (requestParameters["betIds"] == null) {
      throw new runtime.RequiredError(
        "betIds",
        'Required parameter "betIds" was null or undefined when calling betEligibility().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["betIds"] != null) {
      queryParameters["betIds"] = requestParameters["betIds"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xAUTHENTICATION"] != null) {
      headerParameters["X-AUTHENTICATION"] = String(requestParameters["xAUTHENTICATION"]);
    }

    const response = await this.request(
      {
        path: `/bet/mutationEligibility`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => BetEligibilityResponseFromJSON(jsonValue));
  }

  /**
   * Get Bet Mutation Eligibility by Id
   * Get BetMutation Eligibility
   */
  async betEligibility(
    requestParameters: BetEligibilityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<BetEligibilityResponse> {
    const response = await this.betEligibilityRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
