/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  icon: string;
  iconContainer: string;
  link: string;
  notFoundViewContainer: string;
  relatedLinks: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
