/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  disabled: string;
  inverted: string;
  mainLabel: string;
  mainLabelPlaceholder: string;
  progressBar: string;
  secondaryLabel: string;
  secondaryLabelPlaceholder: string;
  statZone: string;
  statZoneLabel: string;
  statZoneLabelPlaceholder: string;
  statZonePlaceholder: string;
  textZone: string;
  textZonePlaceholder: string;
}
export const cssExports: CssExports;
export default cssExports;
