/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  betButtonContainer: string;
  container: string;
  handicap: string;
  labels: string;
  marketContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
