/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  segmentedContainer: string;
  title: string;
  toggleContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
