/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  alertContainer: string;
  betBuilder: string;
  betBuilders: string;
  boostedMultiplesHeader: string;
  boostedMultiplesIcon: string;
  castBetContainer: string;
  combinationSummary: string;
  container: string;
  multiples: string;
  option: string;
  receiptContentContainer: string;
  scrollable: string;
  scrollableDesktop: string;
  scrollableMobile: string;
  single: string;
  singleSignposting: string;
  singles: string;
  summary: string;
}
export const cssExports: CssExports;
export default cssExports;
