/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cbbFloatingButton: string;
  inactive: string;
  withBetslipSelections: string;
  withGradient: string;
}
export const cssExports: CssExports;
export default cssExports;
