/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  modalContent: string;
  modalContentHeader: string;
  modalContentHeaderTitle: string;
  warningMessageContainer: string;
  warningMessageLink: string;
  warningMessageText: string;
  warningMessageTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
