/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  default: string;
  emptyMargins: string;
  emptyTopMargin: string;
  genericViewContainer: string;
  header: string;
  hiddenDesktopItems: string;
  highlighted: string;
  itemsList: string;
  settingsView: string;
}
export const cssExports: CssExports;
export default cssExports;
