import { AppVersion } from "./app-version/AppVersion.types";
import { BrandSettings } from "./brand-settings/BrandSettings.types";
import { Competitions } from "./competitions/Competition.types";
import { CricketFixtures } from "./cricket-fixture/CricketFixture.types";
import { IceHockeyFixtures } from "./ice-hockey-fixture/IceHockeyFixture";
import { AmericanFootballFixtures } from "./american-football-fixture/AmericanFootballFixture";
import { SnookerFixtures } from "./snooker-fixture/SnookerFixture.types";
import { ExchangeMarkets } from "./exchange-markets/ExchangeMarket.types";
import { ExchangeRunners } from "./exchange-runners/ExchangeRunner.types";
import { ExchangeRunnersTraded } from "./ExchangeRunnerTraded.types";
import type { FavouriteMarketsCountMetadatas } from "./favourite-markets-count-metadata/FavouriteMarketsCountMetadata.types";
import type { FavouriteMarketsStates } from "./favourite-markets-state/FavouriteMarketsState.types";
import { FootballFixtures } from "./football-fixture/FootballFixture.types";
import { Games, Jackpots } from "./Gaming.types";
import { ObbLegs } from "./obb-legs/ObbLegs.types";
import { ObbParticipants } from "./obb-participants/ObbParticipants.types";
import { Sports } from "./sports/Sport.types";
import { SportEvents } from "./sport-events/SportEvent.types";
import { SportsbookMarkets } from "./sportsbook-markets/SportsbookMarket.types";
import { SportsbookRunners } from "./sportsbook-runners/SportsbookRunner.types";
import { UserDetailsState } from "./user-details/UserDetailsState";
import { UserPreferencesState } from "./user-preferences/UserPreferences.types";
import { UserWallets } from "./user-wallets/UserWallets.types";
import { Meetings } from "./meetings/Meeting.types";
import { GreyhoundRaceRunners, RaceRunners, Races } from "./races/Race.types";
import { Messages } from "./messages/Messages.types";
import { ThrottlesState } from "./throttles/Throttles.types";
import { ImsPromotions } from "./ims-promotions/ImsPromotion";
import { SettingsPreferences } from "./settings-preferences/SettingsPreferences.types";
import { NotificationsState } from "./notifications/Notifications";
import { WebMessagesState } from "./web-messages/WebMessages.types";
import { TableTennisFixtures } from "./table-tennis-fixture/TableTennisFixture.types";
import { TennisFixtures } from "./tennis-fixture/TennisFixture";
import { BaseballFixtures } from "./baseball-fixture/BaseballFixture";
import { BasketballFixtures } from "./basketball-fixture/BasketballFixture";
import { RugbyUnionFixtures } from "./rugby-union-fixture/RugbyUnionFixture";
import { RugbyLeagueFixtures } from "./rugby-league-fixture/RugbyLeagueFixture";
import { VolleyballFixtures } from "./volleyball-fixture/VolleyballFixture";
import { AustralianRulesFixtures } from "./australian-rules-fixture/AustralianRulesFixture.types";
import { AppContextDetailsState } from "./app-context/AppContextDetailsState.types";
import { LoyaltyMessagingState } from "./loyalty-messaging/LoyaltyMessaging.types";
import { VirtualSports } from "./virtual-sport/VirtualSport.types";
import { VirtualEvents } from "./virtual-event/VirtualEvent.types";
import { VirtualRunners } from "./virtual-runner/VirtualRunner.types";
import { VirtualMarkets } from "./virtual-market/VirtualMarket.types";
import { PopularBettingOpportunities } from "./popular-betting-opportunities/PopularBettingOpportunity.types";
import { ExperimentsState } from "./experiments/Experiments.types";

import { RegulatoryData } from "./regulatory-data/RegulatoryData.types";
import { BetLegs } from "../betting/sportsbook-bets/SportsbookBet.types";
import { ExtraWallets } from "./extra-wallet/ExtraWallet.types";
import { DartsFixtures } from "./darts-fixture/DartsFixture";
import { FootballPlayerFixtureContexts } from "./football-player-fixture-context/FootballPlayerFixtureContext.types";

/**
 * Entities data model interface
 * The main entry for all business entities in the store
 */
export type Entities = {
  readonly productId: string | null;
  readonly appkey: string | null;
  readonly appkeytype: string | null;
  readonly appversion: AppVersion;
  readonly brandSettings: BrandSettings | null;
  readonly sports: Sports;
  readonly competitions: Competitions;
  readonly sportevents: SportEvents;
  readonly sportsbookmarkets: SportsbookMarkets;
  readonly exchangemarkets: ExchangeMarkets;
  readonly sportsbookrunners: SportsbookRunners;
  readonly exchangerunners: ExchangeRunners;
  readonly exchangerunnerstraded: ExchangeRunnersTraded;
  readonly preferences: UserPreferencesState;
  readonly userdetails: UserDetailsState;
  readonly throttles: ThrottlesState;
  readonly wallets: UserWallets;
  readonly favouritemarketscountmetadatas: FavouriteMarketsCountMetadatas;
  readonly favouritemarketsstates: FavouriteMarketsStates;
  readonly footballfixtures: FootballFixtures;
  readonly footballplayerfixturecontexts: FootballPlayerFixtureContexts;
  readonly tabletennisfixtures: TableTennisFixtures;
  readonly tennisfixtures: TennisFixtures;
  readonly baseballfixtures: BaseballFixtures;
  readonly basketballfixtures: BasketballFixtures;
  readonly cricketfixtures: CricketFixtures;
  readonly icehockeyfixtures: IceHockeyFixtures;
  readonly americanfootballfixtures: AmericanFootballFixtures;
  readonly rugbyunionfixtures: RugbyUnionFixtures;
  readonly rugbyleaguefixtures: RugbyLeagueFixtures;
  readonly snookerfixtures: SnookerFixtures;
  readonly volleyballfixtures: VolleyballFixtures;
  readonly australianrulesfixtures: AustralianRulesFixtures;
  readonly dartsfixtures: DartsFixtures;
  readonly games: Games;
  readonly obbLegs: ObbLegs;
  readonly obbParticipants: ObbParticipants;
  readonly jackpots: Jackpots;
  readonly messages: Messages;
  readonly meetings: Meetings;
  readonly races: Races;
  readonly imspromotions: ImsPromotions;
  readonly racerunners: RaceRunners;
  readonly greyhoundracerunners: GreyhoundRaceRunners;
  readonly settingspreferences: SettingsPreferences;
  readonly sportsbookbetlegs: BetLegs;
  readonly notifications: NotificationsState;
  readonly webMessages: WebMessagesState;
  readonly appContextDetails: AppContextDetailsState;
  readonly loyaltyMessages: LoyaltyMessagingState;
  readonly virtualsports: VirtualSports;
  readonly virtualevents: VirtualEvents;
  readonly virtualrunners: VirtualRunners;
  readonly virtualmarkets: VirtualMarkets;
  readonly popularbettingopportunities: PopularBettingOpportunities;
  readonly experiments: ExperimentsState;
  readonly regulatoryData: RegulatoryData;
  readonly extraWallets: ExtraWallets;
};
