/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  alert: string;
  container: string;
  content: string;
  freeBets: string;
  inputFields: string;
  operatorInfo: string;
}
export const cssExports: CssExports;
export default cssExports;
