/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  controls: string;
  header: string;
  headerExperiment: string;
  headerIcon: string;
}
export const cssExports: CssExports;
export default cssExports;
