name: circuit-breaker-hotfix-tag

on:
  pull_request:
    types: [labeled]

jobs:
  set-new-pr-status:
    if: ${{ github.event.label.name == 'hotfix' || github.event.label.name == 'Hotfix' }}
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PULL_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools/circuit-breaker/updateSinglePr.mjs
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update hotfixed PR
        uses: actions/github-script@v7
        id: update-hotfixed-pr
        with:
          script: |
            const { default: updateSinglePr } = await import('${{ github.workspace }}/tools/circuit-breaker/updateSinglePr.mjs');
            const prNumber = ${{ github.event.number }};
            const forceUnblock = "true";
            return updateSinglePr(github, prNumber, forceUnblock);
