name: Trufflehog
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secrets-scan:
    uses: Flutter-Global/uki-infosec-templates/.github/workflows/secrets_scan.yml@master
    with:
      extra_args: "--exclude-paths=trufflehog_exclusions.txt"
      custom_config: true
      fetch-depth: 30
