location ~ /api/tbd/bff-gql/latest(.*)$ {
    # bff-gql - docker-compose service name (which exposes port 8082)
    proxy_pass http://bff-gql:8082/api$1$is_args$args;
    proxy_set_header Host $host;
    proxy_pass_request_headers on;
}

location ~ /api/tbd/bff-gql/v(\d+)(.*)$ {
    # bff-gql - docker-compose service name (which exposes port 8082)
    proxy_pass http://bff-gql:8082/api$2$is_args$args;
    proxy_set_header Host $host;
    proxy_pass_request_headers on;
}
