location ~ /api/tbd/bff-gql/latest(.*)$ {
    proxy_pass http://apitbd/api/tbd/bff-gql/latest$1$is_args$args;
    proxy_method POST;
    proxy_set_header Host $host;
    proxy_pass_request_headers on;
    proxy_set_header Origin "www.paddypower.com";
}

location ~ /api/tbd/bff-gql/(.*)$ {
    proxy_pass http://apitbd/api/tbd/bff-gql/$1$is_args$args;
    proxy_method POST;
    proxy_set_header Host $host;
    proxy_pass_request_headers on;
    proxy_set_header Origin "www.paddypower.com";
}
