/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonWrap: string;
  buttonWrapNo: string;
  caption: string;
  dot: string;
  dots: string;
  fadingOut: string;
  footer: string;
  label: string;
  labelIn: string;
  labelOut: string;
  logo: string;
  predictsLoading: string;
  stack: string;
}
export const cssExports: CssExports;
export default cssExports;
